/*
* Copyright 2017 Ellie Mae, Inc.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
*  1. Redistributions of source code must retain the above copyright notice,
*     this list of conditions and the following disclaimer.
*
*  2. Redistributions in binary form must reproduce the above copyright notice,
*     this list of conditions and the following disclaimer in the documentation
*     and/or other materials provided with the distribution.
*
*  3. Neither the name of the copyright holder nor the names of its
*     contributors may be used to endorse or promote products derived from this
*     software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*/

/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.4.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Elli.Api.Loans.Client;
using Elli.Api.Loans.Model;

namespace Elli.Api.Loans.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAusTrackingLogApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Create AUS Tracking Log record for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Object</returns>
        Object CreateAusTrackingLog (string loanId, AusTrackingLogContract ausTrackingLog, string view = null);

        /// <summary>
        /// Create AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Create AUS Tracking Log record for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreateAusTrackingLogWithHttpInfo (string loanId, AusTrackingLogContract ausTrackingLog, string view = null);
        /// <summary>
        /// Retrieve AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Retrieve a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>AusTrackingLogContract</returns>
        AusTrackingLogContract GetAusTrackingLog (string loanId, string logId);

        /// <summary>
        /// Retrieve AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Retrieve a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>ApiResponse of AusTrackingLogContract</returns>
        ApiResponse<AusTrackingLogContract> GetAusTrackingLogWithHttpInfo (string loanId, string logId);
        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot
        /// </summary>
        /// <remarks>
        /// Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
        Dictionary<string, string> GetAusTrackingLogSnapshot (string loanId, string logId);

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot
        /// </summary>
        /// <remarks>
        /// Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
        ApiResponse<Dictionary<string, string>> GetAusTrackingLogSnapshotWithHttpInfo (string loanId, string logId);
        /// <summary>
        /// Retrieve AUS Tracking Logs
        /// </summary>
        /// <remarks>
        /// Retrieve all AUS Tracking Logs for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>List&lt;AusTrackingLogContract&gt;</returns>
        List<AusTrackingLogContract> GetAusTrackingLogs (string loanId);

        /// <summary>
        /// Retrieve AUS Tracking Logs
        /// </summary>
        /// <remarks>
        /// Retrieve all AUS Tracking Logs for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>ApiResponse of List&lt;AusTrackingLogContract&gt;</returns>
        ApiResponse<List<AusTrackingLogContract>> GetAusTrackingLogsWithHttpInfo (string loanId);
        /// <summary>
        /// Update AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Update a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Object</returns>
        Object UpdateAusTrackingLog (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null);

        /// <summary>
        /// Update AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Update a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> UpdateAusTrackingLogWithHttpInfo (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Create AUS Tracking Log record for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreateAusTrackingLogAsync (string loanId, AusTrackingLogContract ausTrackingLog, string view = null);

        /// <summary>
        /// Create AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Create AUS Tracking Log record for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateAusTrackingLogAsyncWithHttpInfo (string loanId, AusTrackingLogContract ausTrackingLog, string view = null);
        /// <summary>
        /// Retrieve AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Retrieve a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of AusTrackingLogContract</returns>
        System.Threading.Tasks.Task<AusTrackingLogContract> GetAusTrackingLogAsync (string loanId, string logId);

        /// <summary>
        /// Retrieve AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Retrieve a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of ApiResponse (AusTrackingLogContract)</returns>
        System.Threading.Tasks.Task<ApiResponse<AusTrackingLogContract>> GetAusTrackingLogAsyncWithHttpInfo (string loanId, string logId);
        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot
        /// </summary>
        /// <remarks>
        /// Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, string>> GetAusTrackingLogSnapshotAsync (string loanId, string logId);

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot
        /// </summary>
        /// <remarks>
        /// Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, string>>> GetAusTrackingLogSnapshotAsyncWithHttpInfo (string loanId, string logId);
        /// <summary>
        /// Retrieve AUS Tracking Logs
        /// </summary>
        /// <remarks>
        /// Retrieve all AUS Tracking Logs for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>Task of List&lt;AusTrackingLogContract&gt;</returns>
        System.Threading.Tasks.Task<List<AusTrackingLogContract>> GetAusTrackingLogsAsync (string loanId);

        /// <summary>
        /// Retrieve AUS Tracking Logs
        /// </summary>
        /// <remarks>
        /// Retrieve all AUS Tracking Logs for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>Task of ApiResponse (List&lt;AusTrackingLogContract&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<AusTrackingLogContract>>> GetAusTrackingLogsAsyncWithHttpInfo (string loanId);
        /// <summary>
        /// Update AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Update a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> UpdateAusTrackingLogAsync (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null);

        /// <summary>
        /// Update AUS Tracking Log
        /// </summary>
        /// <remarks>
        /// Update a specific AUS Tracking Log for a Loan
        /// </remarks>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateAusTrackingLogAsyncWithHttpInfo (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AusTrackingLogApi : IAusTrackingLogApi
    {
        private Elli.Api.Loans.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AusTrackingLogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AusTrackingLogApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Elli.Api.Loans.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AusTrackingLogApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AusTrackingLogApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Elli.Api.Loans.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Elli.Api.Loans.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create AUS Tracking Log Create AUS Tracking Log record for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Object</returns>
        public Object CreateAusTrackingLog (string loanId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
             ApiResponse<Object> localVarResponse = CreateAusTrackingLogWithHttpInfo(loanId, ausTrackingLog, view);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create AUS Tracking Log Create AUS Tracking Log record for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > CreateAusTrackingLogWithHttpInfo (string loanId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->CreateAusTrackingLog");
            // verify the required parameter 'ausTrackingLog' is set
            if (ausTrackingLog == null)
                throw new ApiException(400, "Missing required parameter 'ausTrackingLog' when calling AusTrackingLogApi->CreateAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (view != null) localVarQueryParams.Add("view", Configuration.ApiClient.ParameterToString(view)); // query parameter
            if (ausTrackingLog != null && ausTrackingLog.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(ausTrackingLog); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ausTrackingLog; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Create AUS Tracking Log Create AUS Tracking Log record for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreateAusTrackingLogAsync (string loanId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
             ApiResponse<Object> localVarResponse = await CreateAusTrackingLogAsyncWithHttpInfo(loanId, ausTrackingLog, view);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create AUS Tracking Log Create AUS Tracking Log record for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> CreateAusTrackingLogAsyncWithHttpInfo (string loanId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->CreateAusTrackingLog");
            // verify the required parameter 'ausTrackingLog' is set
            if (ausTrackingLog == null)
                throw new ApiException(400, "Missing required parameter 'ausTrackingLog' when calling AusTrackingLogApi->CreateAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (view != null) localVarQueryParams.Add("view", Configuration.ApiClient.ParameterToString(view)); // query parameter
            if (ausTrackingLog != null && ausTrackingLog.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(ausTrackingLog); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ausTrackingLog; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Retrieve a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>AusTrackingLogContract</returns>
        public AusTrackingLogContract GetAusTrackingLog (string loanId, string logId)
        {
             ApiResponse<AusTrackingLogContract> localVarResponse = GetAusTrackingLogWithHttpInfo(loanId, logId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Retrieve a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>ApiResponse of AusTrackingLogContract</returns>
        public ApiResponse< AusTrackingLogContract > GetAusTrackingLogWithHttpInfo (string loanId, string logId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLog");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->GetAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AusTrackingLogContract>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AusTrackingLogContract) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AusTrackingLogContract)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Retrieve a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of AusTrackingLogContract</returns>
        public async System.Threading.Tasks.Task<AusTrackingLogContract> GetAusTrackingLogAsync (string loanId, string logId)
        {
             ApiResponse<AusTrackingLogContract> localVarResponse = await GetAusTrackingLogAsyncWithHttpInfo(loanId, logId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve AUS Tracking Log Retrieve a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of ApiResponse (AusTrackingLogContract)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AusTrackingLogContract>> GetAusTrackingLogAsyncWithHttpInfo (string loanId, string logId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLog");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->GetAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AusTrackingLogContract>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AusTrackingLogContract) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AusTrackingLogContract)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
        public Dictionary<string, string> GetAusTrackingLogSnapshot (string loanId, string logId)
        {
             ApiResponse<Dictionary<string, string>> localVarResponse = GetAusTrackingLogSnapshotWithHttpInfo(loanId, logId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
        public ApiResponse< Dictionary<string, string> > GetAusTrackingLogSnapshotWithHttpInfo (string loanId, string logId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLogSnapshot");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->GetAusTrackingLogSnapshot");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}/snapshot";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLogSnapshot", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Dictionary<string, string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, string>)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, string>> GetAusTrackingLogSnapshotAsync (string loanId, string logId)
        {
             ApiResponse<Dictionary<string, string>> localVarResponse = await GetAusTrackingLogSnapshotAsyncWithHttpInfo(loanId, logId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve AUS Tracking Log Snapshot Retrieve AUS Tracking Log Snapshot for an AUS tracking log within a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, string>>> GetAusTrackingLogSnapshotAsyncWithHttpInfo (string loanId, string logId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLogSnapshot");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->GetAusTrackingLogSnapshot");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}/snapshot";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLogSnapshot", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Dictionary<string, string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, string>)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Logs Retrieve all AUS Tracking Logs for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>List&lt;AusTrackingLogContract&gt;</returns>
        public List<AusTrackingLogContract> GetAusTrackingLogs (string loanId)
        {
             ApiResponse<List<AusTrackingLogContract>> localVarResponse = GetAusTrackingLogsWithHttpInfo(loanId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve AUS Tracking Logs Retrieve all AUS Tracking Logs for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>ApiResponse of List&lt;AusTrackingLogContract&gt;</returns>
        public ApiResponse< List<AusTrackingLogContract> > GetAusTrackingLogsWithHttpInfo (string loanId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLogs");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLogs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AusTrackingLogContract>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<AusTrackingLogContract>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AusTrackingLogContract>)));
        }

        /// <summary>
        /// Retrieve AUS Tracking Logs Retrieve all AUS Tracking Logs for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>Task of List&lt;AusTrackingLogContract&gt;</returns>
        public async System.Threading.Tasks.Task<List<AusTrackingLogContract>> GetAusTrackingLogsAsync (string loanId)
        {
             ApiResponse<List<AusTrackingLogContract>> localVarResponse = await GetAusTrackingLogsAsyncWithHttpInfo(loanId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve AUS Tracking Logs Retrieve all AUS Tracking Logs for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <returns>Task of ApiResponse (List&lt;AusTrackingLogContract&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<AusTrackingLogContract>>> GetAusTrackingLogsAsyncWithHttpInfo (string loanId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->GetAusTrackingLogs");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAusTrackingLogs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AusTrackingLogContract>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<AusTrackingLogContract>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AusTrackingLogContract>)));
        }

        /// <summary>
        /// Update AUS Tracking Log Update a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Object</returns>
        public Object UpdateAusTrackingLog (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
             ApiResponse<Object> localVarResponse = UpdateAusTrackingLogWithHttpInfo(loanId, logId, ausTrackingLog, view);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update AUS Tracking Log Update a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > UpdateAusTrackingLogWithHttpInfo (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->UpdateAusTrackingLog");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->UpdateAusTrackingLog");
            // verify the required parameter 'ausTrackingLog' is set
            if (ausTrackingLog == null)
                throw new ApiException(400, "Missing required parameter 'ausTrackingLog' when calling AusTrackingLogApi->UpdateAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter
            if (view != null) localVarQueryParams.Add("view", Configuration.ApiClient.ParameterToString(view)); // query parameter
            if (ausTrackingLog != null && ausTrackingLog.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(ausTrackingLog); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ausTrackingLog; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Update AUS Tracking Log Update a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> UpdateAusTrackingLogAsync (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
             ApiResponse<Object> localVarResponse = await UpdateAusTrackingLogAsyncWithHttpInfo(loanId, logId, ausTrackingLog, view);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update AUS Tracking Log Update a specific AUS Tracking Log for a Loan
        /// </summary>
        /// <exception cref="Elli.Api.Loans.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Unique Identifier of a loan</param>
        /// <param name="logId">Unique Identifier of Aus Tracking Log</param>
        /// <param name="ausTrackingLog">AusTrackingLog</param>
        /// <param name="view">Possible values are: entity - Returns all properties for the loan. id - Returns the ID assigned to the loan. (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UpdateAusTrackingLogAsyncWithHttpInfo (string loanId, string logId, AusTrackingLogContract ausTrackingLog, string view = null)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400, "Missing required parameter 'loanId' when calling AusTrackingLogApi->UpdateAusTrackingLog");
            // verify the required parameter 'logId' is set
            if (logId == null)
                throw new ApiException(400, "Missing required parameter 'logId' when calling AusTrackingLogApi->UpdateAusTrackingLog");
            // verify the required parameter 'ausTrackingLog' is set
            if (ausTrackingLog == null)
                throw new ApiException(400, "Missing required parameter 'ausTrackingLog' when calling AusTrackingLogApi->UpdateAusTrackingLog");

            var localVarPath = "/encompass/v1/loans/{loanId}/ausTrackingLogs/{logId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loanId != null) localVarPathParams.Add("loanId", Configuration.ApiClient.ParameterToString(loanId)); // path parameter
            if (logId != null) localVarPathParams.Add("logId", Configuration.ApiClient.ParameterToString(logId)); // path parameter
            if (view != null) localVarQueryParams.Add("view", Configuration.ApiClient.ParameterToString(view)); // query parameter
            if (ausTrackingLog != null && ausTrackingLog.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(ausTrackingLog); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ausTrackingLog; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAusTrackingLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

    }
}
