/* 
 * Schema
 *
 * Represents schema operations on Loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Schema.Api;
using Elli.Api.Schema.Model;
using Elli.Api.Schema.Client;
using System.Reflection;

namespace Elli.Api.Schema.Test
{
    /// <summary>
    ///  Class for testing LoanContractInterimServicingEscrowDisbursementTransactions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractInterimServicingEscrowDisbursementTransactionsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractInterimServicingEscrowDisbursementTransactions
        //private LoanContractInterimServicingEscrowDisbursementTransactions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractInterimServicingEscrowDisbursementTransactions
            //instance = new LoanContractInterimServicingEscrowDisbursementTransactions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractInterimServicingEscrowDisbursementTransactions
        /// </summary>
        [Test]
        public void LoanContractInterimServicingEscrowDisbursementTransactionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractInterimServicingEscrowDisbursementTransactions
            //Assert.IsInstanceOfType<LoanContractInterimServicingEscrowDisbursementTransactions> (instance, "variable 'instance' is a LoanContractInterimServicingEscrowDisbursementTransactions");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [Test]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }
        /// <summary>
        /// Test the property 'CreatedByName'
        /// </summary>
        [Test]
        public void CreatedByNameTest()
        {
            // TODO unit test for the property 'CreatedByName'
        }
        /// <summary>
        /// Test the property 'CreatedDateTimeUtc'
        /// </summary>
        [Test]
        public void CreatedDateTimeUtcTest()
        {
            // TODO unit test for the property 'CreatedDateTimeUtc'
        }
        /// <summary>
        /// Test the property 'DisbursementDueDate'
        /// </summary>
        [Test]
        public void DisbursementDueDateTest()
        {
            // TODO unit test for the property 'DisbursementDueDate'
        }
        /// <summary>
        /// Test the property 'DisbursementNumber'
        /// </summary>
        [Test]
        public void DisbursementNumberTest()
        {
            // TODO unit test for the property 'DisbursementNumber'
        }
        /// <summary>
        /// Test the property 'DisbursementType'
        /// </summary>
        [Test]
        public void DisbursementTypeTest()
        {
            // TODO unit test for the property 'DisbursementType'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'InstitutionName'
        /// </summary>
        [Test]
        public void InstitutionNameTest()
        {
            // TODO unit test for the property 'InstitutionName'
        }
        /// <summary>
        /// Test the property 'ModifiedById'
        /// </summary>
        [Test]
        public void ModifiedByIdTest()
        {
            // TODO unit test for the property 'ModifiedById'
        }
        /// <summary>
        /// Test the property 'ModifiedByName'
        /// </summary>
        [Test]
        public void ModifiedByNameTest()
        {
            // TODO unit test for the property 'ModifiedByName'
        }
        /// <summary>
        /// Test the property 'ModifiedDateTimeUtc'
        /// </summary>
        [Test]
        public void ModifiedDateTimeUtcTest()
        {
            // TODO unit test for the property 'ModifiedDateTimeUtc'
        }
        /// <summary>
        /// Test the property 'ServicingPaymentMethod'
        /// </summary>
        [Test]
        public void ServicingPaymentMethodTest()
        {
            // TODO unit test for the property 'ServicingPaymentMethod'
        }
        /// <summary>
        /// Test the property 'ServicingTransactionType'
        /// </summary>
        [Test]
        public void ServicingTransactionTypeTest()
        {
            // TODO unit test for the property 'ServicingTransactionType'
        }
        /// <summary>
        /// Test the property 'TransactionAmount'
        /// </summary>
        [Test]
        public void TransactionAmountTest()
        {
            // TODO unit test for the property 'TransactionAmount'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Test]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }

    }

}
