/* 
 * Schema
 *
 * Represents schema operations on Loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Schema.Api;
using Elli.Api.Schema.Model;
using Elli.Api.Schema.Client;
using System.Reflection;

namespace Elli.Api.Schema.Test
{
    /// <summary>
    ///  Class for testing LoanContractServicingDisclosure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractServicingDisclosureTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractServicingDisclosure
        //private LoanContractServicingDisclosure instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractServicingDisclosure
            //instance = new LoanContractServicingDisclosure();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractServicingDisclosure
        /// </summary>
        [Test]
        public void LoanContractServicingDisclosureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractServicingDisclosure
            //Assert.IsInstanceOfType<LoanContractServicingDisclosure> (instance, "variable 'instance' is a LoanContractServicingDisclosure");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisclosurePercent1'
        /// </summary>
        [Test]
        public void DisclosurePercent1Test()
        {
            // TODO unit test for the property 'DisclosurePercent1'
        }
        /// <summary>
        /// Test the property 'DisclosurePercent2'
        /// </summary>
        [Test]
        public void DisclosurePercent2Test()
        {
            // TODO unit test for the property 'DisclosurePercent2'
        }
        /// <summary>
        /// Test the property 'DisclosurePercent3'
        /// </summary>
        [Test]
        public void DisclosurePercent3Test()
        {
            // TODO unit test for the property 'DisclosurePercent3'
        }
        /// <summary>
        /// Test the property 'DisclosureYear1'
        /// </summary>
        [Test]
        public void DisclosureYear1Test()
        {
            // TODO unit test for the property 'DisclosureYear1'
        }
        /// <summary>
        /// Test the property 'DisclosureYear2'
        /// </summary>
        [Test]
        public void DisclosureYear2Test()
        {
            // TODO unit test for the property 'DisclosureYear2'
        }
        /// <summary>
        /// Test the property 'DisclosureYear3'
        /// </summary>
        [Test]
        public void DisclosureYear3Test()
        {
            // TODO unit test for the property 'DisclosureYear3'
        }
        /// <summary>
        /// Test the property 'FiftyOneTo75Indicator'
        /// </summary>
        [Test]
        public void FiftyOneTo75IndicatorTest()
        {
            // TODO unit test for the property 'FiftyOneTo75Indicator'
        }
        /// <summary>
        /// Test the property 'SeventySixTo100Indicator'
        /// </summary>
        [Test]
        public void SeventySixTo100IndicatorTest()
        {
            // TODO unit test for the property 'SeventySixTo100Indicator'
        }
        /// <summary>
        /// Test the property 'ThisEstimateType'
        /// </summary>
        [Test]
        public void ThisEstimateTypeTest()
        {
            // TODO unit test for the property 'ThisEstimateType'
        }
        /// <summary>
        /// Test the property 'ThisInformationType'
        /// </summary>
        [Test]
        public void ThisInformationTypeTest()
        {
            // TODO unit test for the property 'ThisInformationType'
        }
        /// <summary>
        /// Test the property 'ThisIsOurRecordOfTransferingIndicator'
        /// </summary>
        [Test]
        public void ThisIsOurRecordOfTransferingIndicatorTest()
        {
            // TODO unit test for the property 'ThisIsOurRecordOfTransferingIndicator'
        }
        /// <summary>
        /// Test the property 'TwentySixTo50Indicator'
        /// </summary>
        [Test]
        public void TwentySixTo50IndicatorTest()
        {
            // TODO unit test for the property 'TwentySixTo50Indicator'
        }
        /// <summary>
        /// Test the property 'WeAreAbleType'
        /// </summary>
        [Test]
        public void WeAreAbleTypeTest()
        {
            // TODO unit test for the property 'WeAreAbleType'
        }
        /// <summary>
        /// Test the property 'WeDoNotSellMortgageLoansIndicator'
        /// </summary>
        [Test]
        public void WeDoNotSellMortgageLoansIndicatorTest()
        {
            // TODO unit test for the property 'WeDoNotSellMortgageLoansIndicator'
        }
        /// <summary>
        /// Test the property 'WeDoNotServiceMortgageLoansIndicator'
        /// </summary>
        [Test]
        public void WeDoNotServiceMortgageLoansIndicatorTest()
        {
            // TODO unit test for the property 'WeDoNotServiceMortgageLoansIndicator'
        }
        /// <summary>
        /// Test the property 'WeHaveNotServicedMortgLoansIn3YrsIndicator'
        /// </summary>
        [Test]
        public void WeHaveNotServicedMortgLoansIn3YrsIndicatorTest()
        {
            // TODO unit test for the property 'WeHaveNotServicedMortgLoansIn3YrsIndicator'
        }
        /// <summary>
        /// Test the property 'WeHavePreviouslyAssignedIndicator'
        /// </summary>
        [Test]
        public void WeHavePreviouslyAssignedIndicatorTest()
        {
            // TODO unit test for the property 'WeHavePreviouslyAssignedIndicator'
        }
        /// <summary>
        /// Test the property 'WeMayAssignIndicator'
        /// </summary>
        [Test]
        public void WeMayAssignIndicatorTest()
        {
            // TODO unit test for the property 'WeMayAssignIndicator'
        }
        /// <summary>
        /// Test the property 'ZeroTo25Indicator'
        /// </summary>
        [Test]
        public void ZeroTo25IndicatorTest()
        {
            // TODO unit test for the property 'ZeroTo25Indicator'
        }

    }

}
