/* 
 * Schema
 *
 * Represents schema operations on Loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Schema.Api;
using Elli.Api.Schema.Model;
using Elli.Api.Schema.Client;
using System.Reflection;

namespace Elli.Api.Schema.Test
{
    /// <summary>
    ///  Class for testing LoanContractClosingCostLoanEstimate2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractClosingCostLoanEstimate2Tests
    {
        // TODO uncomment below to declare an instance variable for LoanContractClosingCostLoanEstimate2
        //private LoanContractClosingCostLoanEstimate2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractClosingCostLoanEstimate2
            //instance = new LoanContractClosingCostLoanEstimate2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractClosingCostLoanEstimate2
        /// </summary>
        [Test]
        public void LoanContractClosingCostLoanEstimate2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractClosingCostLoanEstimate2
            //Assert.IsInstanceOfType<LoanContractClosingCostLoanEstimate2> (instance, "variable 'instance' is a LoanContractClosingCostLoanEstimate2");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OriginationChargesSubTotal'
        /// </summary>
        [Test]
        public void OriginationChargesSubTotalTest()
        {
            // TODO unit test for the property 'OriginationChargesSubTotal'
        }
        /// <summary>
        /// Test the property 'ServicesYouNotShopSubTotal'
        /// </summary>
        [Test]
        public void ServicesYouNotShopSubTotalTest()
        {
            // TODO unit test for the property 'ServicesYouNotShopSubTotal'
        }
        /// <summary>
        /// Test the property 'ServicesYouShopSubTotal'
        /// </summary>
        [Test]
        public void ServicesYouShopSubTotalTest()
        {
            // TODO unit test for the property 'ServicesYouShopSubTotal'
        }
        /// <summary>
        /// Test the property 'TotalLoanCosts'
        /// </summary>
        [Test]
        public void TotalLoanCostsTest()
        {
            // TODO unit test for the property 'TotalLoanCosts'
        }
        /// <summary>
        /// Test the property 'TaxesGovFeesSubTotal'
        /// </summary>
        [Test]
        public void TaxesGovFeesSubTotalTest()
        {
            // TODO unit test for the property 'TaxesGovFeesSubTotal'
        }
        /// <summary>
        /// Test the property 'PrepaidsSubTotal'
        /// </summary>
        [Test]
        public void PrepaidsSubTotalTest()
        {
            // TODO unit test for the property 'PrepaidsSubTotal'
        }
        /// <summary>
        /// Test the property 'InitialEscrowPaymentClosingSubTotal'
        /// </summary>
        [Test]
        public void InitialEscrowPaymentClosingSubTotalTest()
        {
            // TODO unit test for the property 'InitialEscrowPaymentClosingSubTotal'
        }
        /// <summary>
        /// Test the property 'OtherSubTotal'
        /// </summary>
        [Test]
        public void OtherSubTotalTest()
        {
            // TODO unit test for the property 'OtherSubTotal'
        }
        /// <summary>
        /// Test the property 'TotalOtherCosts'
        /// </summary>
        [Test]
        public void TotalOtherCostsTest()
        {
            // TODO unit test for the property 'TotalOtherCosts'
        }
        /// <summary>
        /// Test the property 'TotalClosingCosts'
        /// </summary>
        [Test]
        public void TotalClosingCostsTest()
        {
            // TODO unit test for the property 'TotalClosingCosts'
        }
        /// <summary>
        /// Test the property 'TotalLoanAndOtherCosts'
        /// </summary>
        [Test]
        public void TotalLoanAndOtherCostsTest()
        {
            // TODO unit test for the property 'TotalLoanAndOtherCosts'
        }
        /// <summary>
        /// Test the property 'LenderCredits'
        /// </summary>
        [Test]
        public void LenderCreditsTest()
        {
            // TODO unit test for the property 'LenderCredits'
        }
        /// <summary>
        /// Test the property 'ClosingCostsFinanced'
        /// </summary>
        [Test]
        public void ClosingCostsFinancedTest()
        {
            // TODO unit test for the property 'ClosingCostsFinanced'
        }
        /// <summary>
        /// Test the property 'DownPayment'
        /// </summary>
        [Test]
        public void DownPaymentTest()
        {
            // TODO unit test for the property 'DownPayment'
        }
        /// <summary>
        /// Test the property 'FundsForBorrower'
        /// </summary>
        [Test]
        public void FundsForBorrowerTest()
        {
            // TODO unit test for the property 'FundsForBorrower'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCredits'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsTest()
        {
            // TODO unit test for the property 'AdjustmentsOtherCredits'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc1'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc1Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc1'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt1'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt1Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt1'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc2'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc2Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc2'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt2'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt2Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt2'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc3'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc3Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc3'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt3'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt3Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt3'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc4'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc4Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc4'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt4'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt4Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt4'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc5'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc5Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc5'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt5'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt5Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt5'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc6'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc6Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc6'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt6'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt6Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt6'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc7'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc7Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc7'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt7'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt7Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt7'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc8'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc8Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc8'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt8'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt8Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt8'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc9'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc9Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc9'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt9'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt9Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt9'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsDesc10'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsDesc10Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsDesc10'
        }
        /// <summary>
        /// Test the property 'AdjustmentsOtherCreditsAmt10'
        /// </summary>
        [Test]
        public void AdjustmentsOtherCreditsAmt10Test()
        {
            // TODO unit test for the property 'AdjustmentsOtherCreditsAmt10'
        }
        /// <summary>
        /// Test the property 'EstimatedCashToCloseSV'
        /// </summary>
        [Test]
        public void EstimatedCashToCloseSVTest()
        {
            // TODO unit test for the property 'EstimatedCashToCloseSV'
        }
        /// <summary>
        /// Test the property 'EstimatedCashToCloseAV'
        /// </summary>
        [Test]
        public void EstimatedCashToCloseAVTest()
        {
            // TODO unit test for the property 'EstimatedCashToCloseAV'
        }
        /// <summary>
        /// Test the property 'FromOrToBorrower'
        /// </summary>
        [Test]
        public void FromOrToBorrowerTest()
        {
            // TODO unit test for the property 'FromOrToBorrower'
        }
        /// <summary>
        /// Test the property 'UseAlternate'
        /// </summary>
        [Test]
        public void UseAlternateTest()
        {
            // TODO unit test for the property 'UseAlternate'
        }
        /// <summary>
        /// Test the property 'IndexMargin'
        /// </summary>
        [Test]
        public void IndexMarginTest()
        {
            // TODO unit test for the property 'IndexMargin'
        }
        /// <summary>
        /// Test the property 'FirstChangeMonthSuffix'
        /// </summary>
        [Test]
        public void FirstChangeMonthSuffixTest()
        {
            // TODO unit test for the property 'FirstChangeMonthSuffix'
        }
        /// <summary>
        /// Test the property 'SubseqChangeMonthSuffix'
        /// </summary>
        [Test]
        public void SubseqChangeMonthSuffixTest()
        {
            // TODO unit test for the property 'SubseqChangeMonthSuffix'
        }
        /// <summary>
        /// Test the property 'FirstChangeFrequencyMonth'
        /// </summary>
        [Test]
        public void FirstChangeFrequencyMonthTest()
        {
            // TODO unit test for the property 'FirstChangeFrequencyMonth'
        }
        /// <summary>
        /// Test the property 'SellerCreditAmount'
        /// </summary>
        [Test]
        public void SellerCreditAmountTest()
        {
            // TODO unit test for the property 'SellerCreditAmount'
        }
        /// <summary>
        /// Test the property 'UnroundedTotalLoanCosts'
        /// </summary>
        [Test]
        public void UnroundedTotalLoanCostsTest()
        {
            // TODO unit test for the property 'UnroundedTotalLoanCosts'
        }
        /// <summary>
        /// Test the property 'UnroundedTotalOtherCosts'
        /// </summary>
        [Test]
        public void UnroundedTotalOtherCostsTest()
        {
            // TODO unit test for the property 'UnroundedTotalOtherCosts'
        }
        /// <summary>
        /// Test the property 'ActualLenderCredits'
        /// </summary>
        [Test]
        public void ActualLenderCreditsTest()
        {
            // TODO unit test for the property 'ActualLenderCredits'
        }
        /// <summary>
        /// Test the property 'ActualSTDLETotalClosingCostJ'
        /// </summary>
        [Test]
        public void ActualSTDLETotalClosingCostJTest()
        {
            // TODO unit test for the property 'ActualSTDLETotalClosingCostJ'
        }
        /// <summary>
        /// Test the property 'ActualSTDLESellerCredits'
        /// </summary>
        [Test]
        public void ActualSTDLESellerCreditsTest()
        {
            // TODO unit test for the property 'ActualSTDLESellerCredits'
        }
        /// <summary>
        /// Test the property 'ThirdPartyPaymentsNotOtherwiseDisclosed'
        /// </summary>
        [Test]
        public void ThirdPartyPaymentsNotOtherwiseDisclosedTest()
        {
            // TODO unit test for the property 'ThirdPartyPaymentsNotOtherwiseDisclosed'
        }
        /// <summary>
        /// Test the property 'UseActualDownPaymentAndClosingCostsFinancedIndicator'
        /// </summary>
        [Test]
        public void UseActualDownPaymentAndClosingCostsFinancedIndicatorTest()
        {
            // TODO unit test for the property 'UseActualDownPaymentAndClosingCostsFinancedIndicator'
        }
        /// <summary>
        /// Test the property 'EstimatedTotalPayoffsAndPaymentsAmount'
        /// </summary>
        [Test]
        public void EstimatedTotalPayoffsAndPaymentsAmountTest()
        {
            // TODO unit test for the property 'EstimatedTotalPayoffsAndPaymentsAmount'
        }
        /// <summary>
        /// Test the property 'ItemizeServiceSectionCType'
        /// </summary>
        [Test]
        public void ItemizeServiceSectionCTypeTest()
        {
            // TODO unit test for the property 'ItemizeServiceSectionCType'
        }

    }

}
