/* 
 * Schema
 *
 * Represents schema operations on Loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Schema.Api;
using Elli.Api.Schema.Model;
using Elli.Api.Schema.Client;
using System.Reflection;

namespace Elli.Api.Schema.Test
{
    /// <summary>
    ///  Class for testing LoanContractUnderwritingConditionLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractUnderwritingConditionLogsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractUnderwritingConditionLogs
        //private LoanContractUnderwritingConditionLogs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractUnderwritingConditionLogs
            //instance = new LoanContractUnderwritingConditionLogs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractUnderwritingConditionLogs
        /// </summary>
        [Test]
        public void LoanContractUnderwritingConditionLogsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractUnderwritingConditionLogs
            //Assert.IsInstanceOfType<LoanContractUnderwritingConditionLogs> (instance, "variable 'instance' is a LoanContractUnderwritingConditionLogs");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AddedBy'
        /// </summary>
        [Test]
        public void AddedByTest()
        {
            // TODO unit test for the property 'AddedBy'
        }
        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Test]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }
        /// <summary>
        /// Test the property 'AllowToClearIndicator'
        /// </summary>
        [Test]
        public void AllowToClearIndicatorTest()
        {
            // TODO unit test for the property 'AllowToClearIndicator'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'ClearedBy'
        /// </summary>
        [Test]
        public void ClearedByTest()
        {
            // TODO unit test for the property 'ClearedBy'
        }
        /// <summary>
        /// Test the property 'CommentList'
        /// </summary>
        [Test]
        public void CommentListTest()
        {
            // TODO unit test for the property 'CommentList'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'DateAddedUtc'
        /// </summary>
        [Test]
        public void DateAddedUtcTest()
        {
            // TODO unit test for the property 'DateAddedUtc'
        }
        /// <summary>
        /// Test the property 'DateClearedUtc'
        /// </summary>
        [Test]
        public void DateClearedUtcTest()
        {
            // TODO unit test for the property 'DateClearedUtc'
        }
        /// <summary>
        /// Test the property 'DateFulfilledUtc'
        /// </summary>
        [Test]
        public void DateFulfilledUtcTest()
        {
            // TODO unit test for the property 'DateFulfilledUtc'
        }
        /// <summary>
        /// Test the property 'DateReceivedUtc'
        /// </summary>
        [Test]
        public void DateReceivedUtcTest()
        {
            // TODO unit test for the property 'DateReceivedUtc'
        }
        /// <summary>
        /// Test the property 'DateRejectedUtc'
        /// </summary>
        [Test]
        public void DateRejectedUtcTest()
        {
            // TODO unit test for the property 'DateRejectedUtc'
        }
        /// <summary>
        /// Test the property 'DateReviewedUtc'
        /// </summary>
        [Test]
        public void DateReviewedUtcTest()
        {
            // TODO unit test for the property 'DateReviewedUtc'
        }
        /// <summary>
        /// Test the property 'DateUtc'
        /// </summary>
        [Test]
        public void DateUtcTest()
        {
            // TODO unit test for the property 'DateUtc'
        }
        /// <summary>
        /// Test the property 'DateWaivedUtc'
        /// </summary>
        [Test]
        public void DateWaivedUtcTest()
        {
            // TODO unit test for the property 'DateWaivedUtc'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'FileAttachmentsMigrated'
        /// </summary>
        [Test]
        public void FileAttachmentsMigratedTest()
        {
            // TODO unit test for the property 'FileAttachmentsMigrated'
        }
        /// <summary>
        /// Test the property 'ForRoleId'
        /// </summary>
        [Test]
        public void ForRoleIdTest()
        {
            // TODO unit test for the property 'ForRoleId'
        }
        /// <summary>
        /// Test the property 'FulfilledBy'
        /// </summary>
        [Test]
        public void FulfilledByTest()
        {
            // TODO unit test for the property 'FulfilledBy'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'IsExternalIndicator'
        /// </summary>
        [Test]
        public void IsExternalIndicatorTest()
        {
            // TODO unit test for the property 'IsExternalIndicator'
        }
        /// <summary>
        /// Test the property 'IsInternalIndicator'
        /// </summary>
        [Test]
        public void IsInternalIndicatorTest()
        {
            // TODO unit test for the property 'IsInternalIndicator'
        }
        /// <summary>
        /// Test the property 'IsSystemSpecificIndicator'
        /// </summary>
        [Test]
        public void IsSystemSpecificIndicatorTest()
        {
            // TODO unit test for the property 'IsSystemSpecificIndicator'
        }
        /// <summary>
        /// Test the property 'LogRecordIndex'
        /// </summary>
        [Test]
        public void LogRecordIndexTest()
        {
            // TODO unit test for the property 'LogRecordIndex'
        }
        /// <summary>
        /// Test the property 'PairId'
        /// </summary>
        [Test]
        public void PairIdTest()
        {
            // TODO unit test for the property 'PairId'
        }
        /// <summary>
        /// Test the property 'PriorTo'
        /// </summary>
        [Test]
        public void PriorToTest()
        {
            // TODO unit test for the property 'PriorTo'
        }
        /// <summary>
        /// Test the property 'ReceivedBy'
        /// </summary>
        [Test]
        public void ReceivedByTest()
        {
            // TODO unit test for the property 'ReceivedBy'
        }
        /// <summary>
        /// Test the property 'RejectedBy'
        /// </summary>
        [Test]
        public void RejectedByTest()
        {
            // TODO unit test for the property 'RejectedBy'
        }
        /// <summary>
        /// Test the property 'ReviewedBy'
        /// </summary>
        [Test]
        public void ReviewedByTest()
        {
            // TODO unit test for the property 'ReviewedBy'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'SystemId'
        /// </summary>
        [Test]
        public void SystemIdTest()
        {
            // TODO unit test for the property 'SystemId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'WaivedBy'
        /// </summary>
        [Test]
        public void WaivedByTest()
        {
            // TODO unit test for the property 'WaivedBy'
        }
        /// <summary>
        /// Test the property 'DateExpiredUtc'
        /// </summary>
        [Test]
        public void DateExpiredUtcTest()
        {
            // TODO unit test for the property 'DateExpiredUtc'
        }
        /// <summary>
        /// Test the property 'Cleared'
        /// </summary>
        [Test]
        public void ClearedTest()
        {
            // TODO unit test for the property 'Cleared'
        }
        /// <summary>
        /// Test the property 'Reviewed'
        /// </summary>
        [Test]
        public void ReviewedTest()
        {
            // TODO unit test for the property 'Reviewed'
        }
        /// <summary>
        /// Test the property 'Waived'
        /// </summary>
        [Test]
        public void WaivedTest()
        {
            // TODO unit test for the property 'Waived'
        }
        /// <summary>
        /// Test the property 'Rejected'
        /// </summary>
        [Test]
        public void RejectedTest()
        {
            // TODO unit test for the property 'Rejected'
        }
        /// <summary>
        /// Test the property 'Fulfilled'
        /// </summary>
        [Test]
        public void FulfilledTest()
        {
            // TODO unit test for the property 'Fulfilled'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Test]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'Expected'
        /// </summary>
        [Test]
        public void ExpectedTest()
        {
            // TODO unit test for the property 'Expected'
        }
        /// <summary>
        /// Test the property 'DateExpected'
        /// </summary>
        [Test]
        public void DateExpectedTest()
        {
            // TODO unit test for the property 'DateExpected'
        }
        /// <summary>
        /// Test the property 'DateRequestedUtc'
        /// </summary>
        [Test]
        public void DateRequestedUtcTest()
        {
            // TODO unit test for the property 'DateRequestedUtc'
        }
        /// <summary>
        /// Test the property 'RequestedBy'
        /// </summary>
        [Test]
        public void RequestedByTest()
        {
            // TODO unit test for the property 'RequestedBy'
        }
        /// <summary>
        /// Test the property 'DateRerequestedUtc'
        /// </summary>
        [Test]
        public void DateRerequestedUtcTest()
        {
            // TODO unit test for the property 'DateRerequestedUtc'
        }
        /// <summary>
        /// Test the property 'RerequestedBy'
        /// </summary>
        [Test]
        public void RerequestedByTest()
        {
            // TODO unit test for the property 'RerequestedBy'
        }
        /// <summary>
        /// Test the property 'DateReceived'
        /// </summary>
        [Test]
        public void DateReceivedTest()
        {
            // TODO unit test for the property 'DateReceived'
        }
        /// <summary>
        /// Test the property 'Received'
        /// </summary>
        [Test]
        public void ReceivedTest()
        {
            // TODO unit test for the property 'Received'
        }
        /// <summary>
        /// Test the property 'Requested'
        /// </summary>
        [Test]
        public void RequestedTest()
        {
            // TODO unit test for the property 'Requested'
        }
        /// <summary>
        /// Test the property 'Rerequested'
        /// </summary>
        [Test]
        public void RerequestedTest()
        {
            // TODO unit test for the property 'Rerequested'
        }
        /// <summary>
        /// Test the property 'IsPastDue'
        /// </summary>
        [Test]
        public void IsPastDueTest()
        {
            // TODO unit test for the property 'IsPastDue'
        }
        /// <summary>
        /// Test the property 'AlertsXml'
        /// </summary>
        [Test]
        public void AlertsXmlTest()
        {
            // TODO unit test for the property 'AlertsXml'
        }
        /// <summary>
        /// Test the property 'CommentListXml'
        /// </summary>
        [Test]
        public void CommentListXmlTest()
        {
            // TODO unit test for the property 'CommentListXml'
        }

    }

}
