/* 
 * Schema
 *
 * Represents schema operations on Loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Schema.Api;
using Elli.Api.Schema.Model;
using Elli.Api.Schema.Client;
using System.Reflection;

namespace Elli.Api.Schema.Test
{
    /// <summary>
    ///  Class for testing LoanContractHtmlEmailLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractHtmlEmailLogsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractHtmlEmailLogs
        //private LoanContractHtmlEmailLogs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractHtmlEmailLogs
            //instance = new LoanContractHtmlEmailLogs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractHtmlEmailLogs
        /// </summary>
        [Test]
        public void LoanContractHtmlEmailLogsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractHtmlEmailLogs
            //Assert.IsInstanceOfType<LoanContractHtmlEmailLogs> (instance, "variable 'instance' is a LoanContractHtmlEmailLogs");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Test]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'CommentList'
        /// </summary>
        [Test]
        public void CommentListTest()
        {
            // TODO unit test for the property 'CommentList'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'DateUtc'
        /// </summary>
        [Test]
        public void DateUtcTest()
        {
            // TODO unit test for the property 'DateUtc'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FileAttachmentsMigrated'
        /// </summary>
        [Test]
        public void FileAttachmentsMigratedTest()
        {
            // TODO unit test for the property 'FileAttachmentsMigrated'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'IsSystemSpecificIndicator'
        /// </summary>
        [Test]
        public void IsSystemSpecificIndicatorTest()
        {
            // TODO unit test for the property 'IsSystemSpecificIndicator'
        }
        /// <summary>
        /// Test the property 'LogRecordIndex'
        /// </summary>
        [Test]
        public void LogRecordIndexTest()
        {
            // TODO unit test for the property 'LogRecordIndex'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Test]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'ReadReceipt'
        /// </summary>
        [Test]
        public void ReadReceiptTest()
        {
            // TODO unit test for the property 'ReadReceipt'
        }
        /// <summary>
        /// Test the property 'SystemId'
        /// </summary>
        [Test]
        public void SystemIdTest()
        {
            // TODO unit test for the property 'SystemId'
        }
        /// <summary>
        /// Test the property 'DocList'
        /// </summary>
        [Test]
        public void DocListTest()
        {
            // TODO unit test for the property 'DocList'
        }

    }

}
