/* 
 * Settings
 *
 * Represents settings operations on Company, Loan, Contact etc.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Settings.Api;
using Elli.Api.Settings.Model;
using Elli.Api.Settings.Client;
using System.Reflection;

namespace Elli.Api.Settings.Test
{
    /// <summary>
    ///  Class for testing OrganizationInfoContractLegalEntityIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrganizationInfoContractLegalEntityIdentifierTests
    {
        // TODO uncomment below to declare an instance variable for OrganizationInfoContractLegalEntityIdentifier
        //private OrganizationInfoContractLegalEntityIdentifier instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrganizationInfoContractLegalEntityIdentifier
            //instance = new OrganizationInfoContractLegalEntityIdentifier();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrganizationInfoContractLegalEntityIdentifier
        /// </summary>
        [Test]
        public void OrganizationInfoContractLegalEntityIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrganizationInfoContractLegalEntityIdentifier
            //Assert.IsInstanceOfType<OrganizationInfoContractLegalEntityIdentifier> (instance, "variable 'instance' is a OrganizationInfoContractLegalEntityIdentifier");
        }

        /// <summary>
        /// Test the property 'UseParentInformation'
        /// </summary>
        [Test]
        public void UseParentInformationTest()
        {
            // TODO unit test for the property 'UseParentInformation'
        }
        /// <summary>
        /// Test the property 'HmdaProfile'
        /// </summary>
        [Test]
        public void HmdaProfileTest()
        {
            // TODO unit test for the property 'HmdaProfile'
        }
        /// <summary>
        /// Test the property 'Lei'
        /// </summary>
        [Test]
        public void LeiTest()
        {
            // TODO unit test for the property 'Lei'
        }

    }

}
