/* 
 * Loan
 *
 * APIs to manage eFolder related entities - document and attachment.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.EFolder.Api;
using Elli.Api.Loans.EFolder.Model;
using Elli.Api.Loans.EFolder.Client;
using System.Reflection;

namespace Elli.Api.Loans.EFolder.Test
{
    /// <summary>
    ///  Class for testing EFolderDocumentContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EFolderDocumentContractTests
    {
        // TODO uncomment below to declare an instance variable for EFolderDocumentContract
        //private EFolderDocumentContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EFolderDocumentContract
            //instance = new EFolderDocumentContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EFolderDocumentContract
        /// </summary>
        [Test]
        public void EFolderDocumentContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EFolderDocumentContract
            //Assert.IsInstanceOfType<EFolderDocumentContract> (instance, "variable 'instance' is a EFolderDocumentContract");
        }

        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'TitleWithIndex'
        /// </summary>
        [Test]
        public void TitleWithIndexTest()
        {
            // TODO unit test for the property 'TitleWithIndex'
        }
        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Test]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'MilestoneId'
        /// </summary>
        [Test]
        public void MilestoneIdTest()
        {
            // TODO unit test for the property 'MilestoneId'
        }
        /// <summary>
        /// Test the property 'WebCenterAllowed'
        /// </summary>
        [Test]
        public void WebCenterAllowedTest()
        {
            // TODO unit test for the property 'WebCenterAllowed'
        }
        /// <summary>
        /// Test the property 'TpoAllowed'
        /// </summary>
        [Test]
        public void TpoAllowedTest()
        {
            // TODO unit test for the property 'TpoAllowed'
        }
        /// <summary>
        /// Test the property 'ThirdPartyAllowed'
        /// </summary>
        [Test]
        public void ThirdPartyAllowedTest()
        {
            // TODO unit test for the property 'ThirdPartyAllowed'
        }
        /// <summary>
        /// Test the property 'IsRequested'
        /// </summary>
        [Test]
        public void IsRequestedTest()
        {
            // TODO unit test for the property 'IsRequested'
        }
        /// <summary>
        /// Test the property 'RequestedBy'
        /// </summary>
        [Test]
        public void RequestedByTest()
        {
            // TODO unit test for the property 'RequestedBy'
        }
        /// <summary>
        /// Test the property 'IsRerequested'
        /// </summary>
        [Test]
        public void IsRerequestedTest()
        {
            // TODO unit test for the property 'IsRerequested'
        }
        /// <summary>
        /// Test the property 'DateRerequested'
        /// </summary>
        [Test]
        public void DateRerequestedTest()
        {
            // TODO unit test for the property 'DateRerequested'
        }
        /// <summary>
        /// Test the property 'RerequestedBy'
        /// </summary>
        [Test]
        public void RerequestedByTest()
        {
            // TODO unit test for the property 'RerequestedBy'
        }
        /// <summary>
        /// Test the property 'DaysDue'
        /// </summary>
        [Test]
        public void DaysDueTest()
        {
            // TODO unit test for the property 'DaysDue'
        }
        /// <summary>
        /// Test the property 'IsReceived'
        /// </summary>
        [Test]
        public void IsReceivedTest()
        {
            // TODO unit test for the property 'IsReceived'
        }
        /// <summary>
        /// Test the property 'ReceivedBy'
        /// </summary>
        [Test]
        public void ReceivedByTest()
        {
            // TODO unit test for the property 'ReceivedBy'
        }
        /// <summary>
        /// Test the property 'DaysTillExpire'
        /// </summary>
        [Test]
        public void DaysTillExpireTest()
        {
            // TODO unit test for the property 'DaysTillExpire'
        }
        /// <summary>
        /// Test the property 'IsReviewed'
        /// </summary>
        [Test]
        public void IsReviewedTest()
        {
            // TODO unit test for the property 'IsReviewed'
        }
        /// <summary>
        /// Test the property 'ReviewedBy'
        /// </summary>
        [Test]
        public void ReviewedByTest()
        {
            // TODO unit test for the property 'ReviewedBy'
        }
        /// <summary>
        /// Test the property 'IsReadyForUw'
        /// </summary>
        [Test]
        public void IsReadyForUwTest()
        {
            // TODO unit test for the property 'IsReadyForUw'
        }
        /// <summary>
        /// Test the property 'ReadyForUwBy'
        /// </summary>
        [Test]
        public void ReadyForUwByTest()
        {
            // TODO unit test for the property 'ReadyForUwBy'
        }
        /// <summary>
        /// Test the property 'IsReadyToShip'
        /// </summary>
        [Test]
        public void IsReadyToShipTest()
        {
            // TODO unit test for the property 'IsReadyToShip'
        }
        /// <summary>
        /// Test the property 'ReadyToShipBy'
        /// </summary>
        [Test]
        public void ReadyToShipByTest()
        {
            // TODO unit test for the property 'ReadyToShipBy'
        }
        /// <summary>
        /// Test the property 'DateExpires'
        /// </summary>
        [Test]
        public void DateExpiresTest()
        {
            // TODO unit test for the property 'DateExpires'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'RequestedFrom'
        /// </summary>
        [Test]
        public void RequestedFromTest()
        {
            // TODO unit test for the property 'RequestedFrom'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'EmnSignature'
        /// </summary>
        [Test]
        public void EmnSignatureTest()
        {
            // TODO unit test for the property 'EmnSignature'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDate'
        /// </summary>
        [Test]
        public void StatusDateTest()
        {
            // TODO unit test for the property 'StatusDate'
        }
        /// <summary>
        /// Test the property 'DateRequested'
        /// </summary>
        [Test]
        public void DateRequestedTest()
        {
            // TODO unit test for the property 'DateRequested'
        }
        /// <summary>
        /// Test the property 'DateExpected'
        /// </summary>
        [Test]
        public void DateExpectedTest()
        {
            // TODO unit test for the property 'DateExpected'
        }
        /// <summary>
        /// Test the property 'DateReceived'
        /// </summary>
        [Test]
        public void DateReceivedTest()
        {
            // TODO unit test for the property 'DateReceived'
        }
        /// <summary>
        /// Test the property 'DateReviewed'
        /// </summary>
        [Test]
        public void DateReviewedTest()
        {
            // TODO unit test for the property 'DateReviewed'
        }
        /// <summary>
        /// Test the property 'DateReadyForUw'
        /// </summary>
        [Test]
        public void DateReadyForUwTest()
        {
            // TODO unit test for the property 'DateReadyForUw'
        }
        /// <summary>
        /// Test the property 'DateReadyToShip'
        /// </summary>
        [Test]
        public void DateReadyToShipTest()
        {
            // TODO unit test for the property 'DateReadyToShip'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
