/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractCustomFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractCustomFieldsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractCustomFields
        //private LoanContractCustomFields instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractCustomFields
            //instance = new LoanContractCustomFields();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractCustomFields
        /// </summary>
        [Test]
        public void LoanContractCustomFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractCustomFields
            //Assert.IsInstanceOfType<LoanContractCustomFields> (instance, "variable 'instance' is a LoanContractCustomFields");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DateValue'
        /// </summary>
        [Test]
        public void DateValueTest()
        {
            // TODO unit test for the property 'DateValue'
        }
        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Test]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'NumericValue'
        /// </summary>
        [Test]
        public void NumericValueTest()
        {
            // TODO unit test for the property 'NumericValue'
        }
        /// <summary>
        /// Test the property 'StringValue'
        /// </summary>
        [Test]
        public void StringValueTest()
        {
            // TODO unit test for the property 'StringValue'
        }

    }

}
