/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractContactTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractContact
        //private LoanContractContact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractContact
            //instance = new LoanContractContact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractContact
        /// </summary>
        [Test]
        public void LoanContractContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractContact
            //Assert.IsInstanceOfType<LoanContractContact> (instance, "variable 'instance' is a LoanContractContact");
        }

        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Test]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'EntityName'
        /// </summary>
        [Test]
        public void EntityNameTest()
        {
            // TODO unit test for the property 'EntityName'
        }
        /// <summary>
        /// Test the property 'EntityUri'
        /// </summary>
        [Test]
        public void EntityUriTest()
        {
            // TODO unit test for the property 'EntityUri'
        }

    }

}
