/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractElliUCDFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractElliUCDFieldsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractElliUCDFields
        //private LoanContractElliUCDFields instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractElliUCDFields
            //instance = new LoanContractElliUCDFields();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractElliUCDFields
        /// </summary>
        [Test]
        public void LoanContractElliUCDFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractElliUCDFields
            //Assert.IsInstanceOfType<LoanContractElliUCDFields> (instance, "variable 'instance' is a LoanContractElliUCDFields");
        }

        /// <summary>
        /// Test the property 'LeFields'
        /// </summary>
        [Test]
        public void LeFieldsTest()
        {
            // TODO unit test for the property 'LeFields'
        }
        /// <summary>
        /// Test the property 'CdFields'
        /// </summary>
        [Test]
        public void CdFieldsTest()
        {
            // TODO unit test for the property 'CdFields'
        }

    }

}
