/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractNonVols
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractNonVolsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractNonVols
        //private LoanContractNonVols instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractNonVols
            //instance = new LoanContractNonVols();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractNonVols
        /// </summary>
        [Test]
        public void LoanContractNonVolsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractNonVols
            //Assert.IsInstanceOfType<LoanContractNonVols> (instance, "variable 'instance' is a LoanContractNonVols");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'NonVolIndex'
        /// </summary>
        [Test]
        public void NonVolIndexTest()
        {
            // TODO unit test for the property 'NonVolIndex'
        }
        /// <summary>
        /// Test the property 'NonVolId'
        /// </summary>
        [Test]
        public void NonVolIdTest()
        {
            // TODO unit test for the property 'NonVolId'
        }
        /// <summary>
        /// Test the property 'AdjustmentDescription'
        /// </summary>
        [Test]
        public void AdjustmentDescriptionTest()
        {
            // TODO unit test for the property 'AdjustmentDescription'
        }
        /// <summary>
        /// Test the property 'AdjustmentOtherDescription'
        /// </summary>
        [Test]
        public void AdjustmentOtherDescriptionTest()
        {
            // TODO unit test for the property 'AdjustmentOtherDescription'
        }
        /// <summary>
        /// Test the property 'AdjustmentType'
        /// </summary>
        [Test]
        public void AdjustmentTypeTest()
        {
            // TODO unit test for the property 'AdjustmentType'
        }
        /// <summary>
        /// Test the property 'AdjustmentAmount'
        /// </summary>
        [Test]
        public void AdjustmentAmountTest()
        {
            // TODO unit test for the property 'AdjustmentAmount'
        }
        /// <summary>
        /// Test the property 'IncludedIndicator'
        /// </summary>
        [Test]
        public void IncludedIndicatorTest()
        {
            // TODO unit test for the property 'IncludedIndicator'
        }
        /// <summary>
        /// Test the property 'POCIndicator'
        /// </summary>
        [Test]
        public void POCIndicatorTest()
        {
            // TODO unit test for the property 'POCIndicator'
        }
        /// <summary>
        /// Test the property 'PaidBy'
        /// </summary>
        [Test]
        public void PaidByTest()
        {
            // TODO unit test for the property 'PaidBy'
        }
        /// <summary>
        /// Test the property 'PrincipalCureAddendum'
        /// </summary>
        [Test]
        public void PrincipalCureAddendumTest()
        {
            // TODO unit test for the property 'PrincipalCureAddendum'
        }
        /// <summary>
        /// Test the property 'PaidTo'
        /// </summary>
        [Test]
        public void PaidToTest()
        {
            // TODO unit test for the property 'PaidTo'
        }

    }

}
