/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractTrustAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractTrustAccountTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractTrustAccount
        //private LoanContractTrustAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractTrustAccount
            //instance = new LoanContractTrustAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractTrustAccount
        /// </summary>
        [Test]
        public void LoanContractTrustAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractTrustAccount
            //Assert.IsInstanceOfType<LoanContractTrustAccount> (instance, "variable 'instance' is a LoanContractTrustAccount");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Total1'
        /// </summary>
        [Test]
        public void Total1Test()
        {
            // TODO unit test for the property 'Total1'
        }
        /// <summary>
        /// Test the property 'Total2'
        /// </summary>
        [Test]
        public void Total2Test()
        {
            // TODO unit test for the property 'Total2'
        }
        /// <summary>
        /// Test the property 'TrustAccountItems'
        /// </summary>
        [Test]
        public void TrustAccountItemsTest()
        {
            // TODO unit test for the property 'TrustAccountItems'
        }

    }

}
