/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractHud1EsHud1EsPayTos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractHud1EsHud1EsPayTosTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractHud1EsHud1EsPayTos
        //private LoanContractHud1EsHud1EsPayTos instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractHud1EsHud1EsPayTos
            //instance = new LoanContractHud1EsHud1EsPayTos();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractHud1EsHud1EsPayTos
        /// </summary>
        [Test]
        public void LoanContractHud1EsHud1EsPayTosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractHud1EsHud1EsPayTos
            //Assert.IsInstanceOfType<LoanContractHud1EsHud1EsPayTos> (instance, "variable 'instance' is a LoanContractHud1EsHud1EsPayTos");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AmountLastPay'
        /// </summary>
        [Test]
        public void AmountLastPayTest()
        {
            // TODO unit test for the property 'AmountLastPay'
        }
        /// <summary>
        /// Test the property 'AmountNextDue'
        /// </summary>
        [Test]
        public void AmountNextDueTest()
        {
            // TODO unit test for the property 'AmountNextDue'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Test]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }
        /// <summary>
        /// Test the property 'CoverageAmount'
        /// </summary>
        [Test]
        public void CoverageAmountTest()
        {
            // TODO unit test for the property 'CoverageAmount'
        }
        /// <summary>
        /// Test the property 'DatePaid'
        /// </summary>
        [Test]
        public void DatePaidTest()
        {
            // TODO unit test for the property 'DatePaid'
        }
        /// <summary>
        /// Test the property 'DelinquentDate'
        /// </summary>
        [Test]
        public void DelinquentDateTest()
        {
            // TODO unit test for the property 'DelinquentDate'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'FeeType'
        /// </summary>
        [Test]
        public void FeeTypeTest()
        {
            // TODO unit test for the property 'FeeType'
        }
        /// <summary>
        /// Test the property 'Hud1EsPayToIndex'
        /// </summary>
        [Test]
        public void Hud1EsPayToIndexTest()
        {
            // TODO unit test for the property 'Hud1EsPayToIndex'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NextDueDate'
        /// </summary>
        [Test]
        public void NextDueDateTest()
        {
            // TODO unit test for the property 'NextDueDate'
        }
        /// <summary>
        /// Test the property 'PaymentSchedule'
        /// </summary>
        [Test]
        public void PaymentScheduleTest()
        {
            // TODO unit test for the property 'PaymentSchedule'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'PolicyNumber'
        /// </summary>
        [Test]
        public void PolicyNumberTest()
        {
            // TODO unit test for the property 'PolicyNumber'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Test]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }
        /// <summary>
        /// Test the property 'RenewalDate'
        /// </summary>
        [Test]
        public void RenewalDateTest()
        {
            // TODO unit test for the property 'RenewalDate'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'MaxDeductiblePercentage'
        /// </summary>
        [Test]
        public void MaxDeductiblePercentageTest()
        {
            // TODO unit test for the property 'MaxDeductiblePercentage'
        }
        /// <summary>
        /// Test the property 'MaxDeductibleAmount'
        /// </summary>
        [Test]
        public void MaxDeductibleAmountTest()
        {
            // TODO unit test for the property 'MaxDeductibleAmount'
        }

    }

}
