/* 
 * Tools
 *
 * Represents calculations applied on a loan
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Tools.Api;
using Elli.Api.Tools.Model;
using Elli.Api.Tools.Client;
using System.Reflection;

namespace Elli.Api.Tools.Test
{
    /// <summary>
    ///  Class for testing LoanContractCustomModelFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractCustomModelFieldsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractCustomModelFields
        //private LoanContractCustomModelFields instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractCustomModelFields
            //instance = new LoanContractCustomModelFields();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractCustomModelFields
        /// </summary>
        [Test]
        public void LoanContractCustomModelFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractCustomModelFields
            //Assert.IsInstanceOfType<LoanContractCustomModelFields> (instance, "variable 'instance' is a LoanContractCustomModelFields");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProvideAmortizationScenario'
        /// </summary>
        [Test]
        public void ProvideAmortizationScenarioTest()
        {
            // TODO unit test for the property 'ProvideAmortizationScenario'
        }
        /// <summary>
        /// Test the property 'ProvideWorstCaseScenario'
        /// </summary>
        [Test]
        public void ProvideWorstCaseScenarioTest()
        {
            // TODO unit test for the property 'ProvideWorstCaseScenario'
        }
        /// <summary>
        /// Test the property 'ProvideBestCaseScenario'
        /// </summary>
        [Test]
        public void ProvideBestCaseScenarioTest()
        {
            // TODO unit test for the property 'ProvideBestCaseScenario'
        }
        /// <summary>
        /// Test the property 'ProvideFHAScenario'
        /// </summary>
        [Test]
        public void ProvideFHAScenarioTest()
        {
            // TODO unit test for the property 'ProvideFHAScenario'
        }

    }

}
