/* 
 * Credit
 *
 * Credit APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Services.Api;
using Elli.Api.Services.Model;
using Elli.Api.Services.Client;
using System.Reflection;

namespace Elli.Api.Services.Test
{
    /// <summary>
    ///  Class for testing ProductPreferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductPreferencesTests
    {
        // TODO uncomment below to declare an instance variable for ProductPreferences
        //private ProductPreferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductPreferences
            //instance = new ProductPreferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductPreferences
        /// </summary>
        [Test]
        public void ProductPreferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductPreferences
            //Assert.IsInstanceOfType<ProductPreferences> (instance, "variable 'instance' is a ProductPreferences");
        }

        /// <summary>
        /// Test the property 'ImportLiabilities'
        /// </summary>
        [Test]
        public void ImportLiabilitiesTest()
        {
            // TODO unit test for the property 'ImportLiabilities'
        }
        /// <summary>
        /// Test the property 'ExcludeZeroforImportLiabilities'
        /// </summary>
        [Test]
        public void ExcludeZeroforImportLiabilitiesTest()
        {
            // TODO unit test for the property 'ExcludeZeroforImportLiabilities'
        }

    }

}
