/* 
 * Credit
 *
 * Credit APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Services.Api;
using Elli.Api.Services.Model;
using Elli.Api.Services.Client;
using System.Reflection;

namespace Elli.Api.Services.Test
{
    /// <summary>
    ///  Class for testing Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseTests
    {
        // TODO uncomment below to declare an instance variable for Response
        //private Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Response
            //instance = new Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Response
        /// </summary>
        [Test]
        public void ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Response
            //Assert.IsInstanceOfType<Response> (instance, "variable 'instance' is a Response");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

    }

}
