/*
* Copyright 2017 Ellie Mae, Inc.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
*  1. Redistributions of source code must retain the above copyright notice,
*     this list of conditions and the following disclaimer.
*
*  2. Redistributions in binary form must reproduce the above copyright notice,
*     this list of conditions and the following disclaimer in the documentation
*     and/or other materials provided with the distribution.
*
*  3. Neither the name of the copyright holder nor the names of its
*     contributors may be used to endorse or promote products derived from this
*     software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*/

/* 
 * Credit
 *
 * Credit APIs
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Elli.Api.Services.Client;
using Elli.Api.Services.Model;

namespace Elli.Api.Services.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServiceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a credit transaction&#39;s status.
        /// </summary>
        /// <remarks>
        /// Retrieves details on a service order transaction.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>ResourceTransaction</returns>
        ResourceTransaction GetOrderStatus (int? partnerId, string transactionId, bool? generateFileUrls = null);

        /// <summary>
        /// Get a credit transaction&#39;s status.
        /// </summary>
        /// <remarks>
        /// Retrieves details on a service order transaction.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>ApiResponse of ResourceTransaction</returns>
        ApiResponse<ResourceTransaction> GetOrderStatusWithHttpInfo (int? partnerId, string transactionId, bool? generateFileUrls = null);
        /// <summary>
        /// Order Service.
        /// </summary>
        /// <remarks>
        /// Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns></returns>
        void OrderService (int? partnerId, OrderServiceRequest product);

        /// <summary>
        /// Order Service.
        /// </summary>
        /// <remarks>
        /// Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> OrderServiceWithHttpInfo (int? partnerId, OrderServiceRequest product);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get a credit transaction&#39;s status.
        /// </summary>
        /// <remarks>
        /// Retrieves details on a service order transaction.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>Task of ResourceTransaction</returns>
        System.Threading.Tasks.Task<ResourceTransaction> GetOrderStatusAsync (int? partnerId, string transactionId, bool? generateFileUrls = null);

        /// <summary>
        /// Get a credit transaction&#39;s status.
        /// </summary>
        /// <remarks>
        /// Retrieves details on a service order transaction.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>Task of ApiResponse (ResourceTransaction)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResourceTransaction>> GetOrderStatusAsyncWithHttpInfo (int? partnerId, string transactionId, bool? generateFileUrls = null);
        /// <summary>
        /// Order Service.
        /// </summary>
        /// <remarks>
        /// Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task OrderServiceAsync (int? partnerId, OrderServiceRequest product);

        /// <summary>
        /// Order Service.
        /// </summary>
        /// <remarks>
        /// Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </remarks>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> OrderServiceAsyncWithHttpInfo (int? partnerId, OrderServiceRequest product);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ServiceApi : IServiceApi
    {
        private Elli.Api.Services.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ServiceApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Elli.Api.Services.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ServiceApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Elli.Api.Services.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Elli.Api.Services.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get a credit transaction&#39;s status. Retrieves details on a service order transaction.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>ResourceTransaction</returns>
        public ResourceTransaction GetOrderStatus (int? partnerId, string transactionId, bool? generateFileUrls = null)
        {
             ApiResponse<ResourceTransaction> localVarResponse = GetOrderStatusWithHttpInfo(partnerId, transactionId, generateFileUrls);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a credit transaction&#39;s status. Retrieves details on a service order transaction.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>ApiResponse of ResourceTransaction</returns>
        public ApiResponse< ResourceTransaction > GetOrderStatusWithHttpInfo (int? partnerId, string transactionId, bool? generateFileUrls = null)
        {
            // verify the required parameter 'partnerId' is set
            if (partnerId == null)
                throw new ApiException(400, "Missing required parameter 'partnerId' when calling ServiceApi->GetOrderStatus");
            // verify the required parameter 'transactionId' is set
            if (transactionId == null)
                throw new ApiException(400, "Missing required parameter 'transactionId' when calling ServiceApi->GetOrderStatus");

            var localVarPath = "/services/v1/partners/{partnerId}/transactions/{transactionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (partnerId != null) localVarPathParams.Add("partnerId", Configuration.ApiClient.ParameterToString(partnerId)); // path parameter
            if (transactionId != null) localVarPathParams.Add("transactionId", Configuration.ApiClient.ParameterToString(transactionId)); // path parameter
            if (generateFileUrls != null) localVarQueryParams.Add("generateFileUrls", Configuration.ApiClient.ParameterToString(generateFileUrls)); // query parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrderStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResourceTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResourceTransaction) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResourceTransaction)));
        }

        /// <summary>
        /// Get a credit transaction&#39;s status. Retrieves details on a service order transaction.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>Task of ResourceTransaction</returns>
        public async System.Threading.Tasks.Task<ResourceTransaction> GetOrderStatusAsync (int? partnerId, string transactionId, bool? generateFileUrls = null)
        {
             ApiResponse<ResourceTransaction> localVarResponse = await GetOrderStatusAsyncWithHttpInfo(partnerId, transactionId, generateFileUrls);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a credit transaction&#39;s status. Retrieves details on a service order transaction.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="transactionId">The unique identifier of the transaction provided in the response header when the order was submitted.</param>
        /// <param name="generateFileUrls">Generate an accessible URL and populate the URL key for each of the resources returned by the Partner as a part of their service response. &lt;br&gt;&lt;/br&gt; &lt;b&gt;Note:&lt;/b&gt; The URL&#39;s generated are temporarily accessible - time to expiration is 300 seconds (5 minutes). (optional)</param>
        /// <returns>Task of ApiResponse (ResourceTransaction)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResourceTransaction>> GetOrderStatusAsyncWithHttpInfo (int? partnerId, string transactionId, bool? generateFileUrls = null)
        {
            // verify the required parameter 'partnerId' is set
            if (partnerId == null)
                throw new ApiException(400, "Missing required parameter 'partnerId' when calling ServiceApi->GetOrderStatus");
            // verify the required parameter 'transactionId' is set
            if (transactionId == null)
                throw new ApiException(400, "Missing required parameter 'transactionId' when calling ServiceApi->GetOrderStatus");

            var localVarPath = "/services/v1/partners/{partnerId}/transactions/{transactionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (partnerId != null) localVarPathParams.Add("partnerId", Configuration.ApiClient.ParameterToString(partnerId)); // path parameter
            if (transactionId != null) localVarPathParams.Add("transactionId", Configuration.ApiClient.ParameterToString(transactionId)); // path parameter
            if (generateFileUrls != null) localVarQueryParams.Add("generateFileUrls", Configuration.ApiClient.ParameterToString(generateFileUrls)); // query parameter

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrderStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResourceTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResourceTransaction) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResourceTransaction)));
        }

        /// <summary>
        /// Order Service. Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns></returns>
        public void OrderService (int? partnerId, OrderServiceRequest product)
        {
             OrderServiceWithHttpInfo(partnerId, product);
        }

        /// <summary>
        /// Order Service. Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> OrderServiceWithHttpInfo (int? partnerId, OrderServiceRequest product)
        {
            // verify the required parameter 'partnerId' is set
            if (partnerId == null)
                throw new ApiException(400, "Missing required parameter 'partnerId' when calling ServiceApi->OrderService");
            // verify the required parameter 'product' is set
            if (product == null)
                throw new ApiException(400, "Missing required parameter 'product' when calling ServiceApi->OrderService");

            var localVarPath = "/services/v1/partners/{partnerId}/transactions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (partnerId != null) localVarPathParams.Add("partnerId", Configuration.ApiClient.ParameterToString(partnerId)); // path parameter
            if (product != null && product.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(product); // http body (model) parameter
            }
            else
            {
                localVarPostBody = product; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OrderService", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Order Service. Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task OrderServiceAsync (int? partnerId, OrderServiceRequest product)
        {
             await OrderServiceAsyncWithHttpInfo(partnerId, product);

        }

        /// <summary>
        /// Order Service. Submits an order for a service and creates a transaction object. The response header includes the transactionId that is used to retrieve the results from the service provider.
        /// </summary>
        /// <exception cref="Elli.Api.Services.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="partnerId">Ellie Mae&#39;s Partner ID for the service provider. Partner IDs are listed on the Credit Partners and Samples page.</param>
        /// <param name="product">The product data elements that comprise of the transactions request object. Encapsulates information about the loan in whose context the service is being placed, product name, product options/configurations, service credentials to authenticate with the service provider and user preferences.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> OrderServiceAsyncWithHttpInfo (int? partnerId, OrderServiceRequest product)
        {
            // verify the required parameter 'partnerId' is set
            if (partnerId == null)
                throw new ApiException(400, "Missing required parameter 'partnerId' when calling ServiceApi->OrderService");
            // verify the required parameter 'product' is set
            if (product == null)
                throw new ApiException(400, "Missing required parameter 'product' when calling ServiceApi->OrderService");

            var localVarPath = "/services/v1/partners/{partnerId}/transactions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (partnerId != null) localVarPathParams.Add("partnerId", Configuration.ApiClient.ParameterToString(partnerId)); // path parameter
            if (product != null && product.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(product); // http body (model) parameter
            }
            else
            {
                localVarPostBody = product; // byte array
            }

            // authentication (bearerAuth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OrderService", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
