/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing DisclosureTracking2015Contract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DisclosureTracking2015ContractTests
    {
        // TODO uncomment below to declare an instance variable for DisclosureTracking2015Contract
        //private DisclosureTracking2015Contract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DisclosureTracking2015Contract
            //instance = new DisclosureTracking2015Contract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DisclosureTracking2015Contract
        /// </summary>
        [Test]
        public void DisclosureTracking2015ContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DisclosureTracking2015Contract
            //Assert.IsInstanceOfType<DisclosureTracking2015Contract> (instance, "variable 'instance' is a DisclosureTracking2015Contract");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Test]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }
        /// <summary>
        /// Test the property 'BorrowerPair'
        /// </summary>
        [Test]
        public void BorrowerPairTest()
        {
            // TODO unit test for the property 'BorrowerPair'
        }
        /// <summary>
        /// Test the property 'CommentList'
        /// </summary>
        [Test]
        public void CommentListTest()
        {
            // TODO unit test for the property 'CommentList'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'ContainCD'
        /// </summary>
        [Test]
        public void ContainCDTest()
        {
            // TODO unit test for the property 'ContainCD'
        }
        /// <summary>
        /// Test the property 'ContainLE'
        /// </summary>
        [Test]
        public void ContainLETest()
        {
            // TODO unit test for the property 'ContainLE'
        }
        /// <summary>
        /// Test the property 'DisclosedBy'
        /// </summary>
        [Test]
        public void DisclosedByTest()
        {
            // TODO unit test for the property 'DisclosedBy'
        }
        /// <summary>
        /// Test the property 'DisclosedMethod'
        /// </summary>
        [Test]
        public void DisclosedMethodTest()
        {
            // TODO unit test for the property 'DisclosedMethod'
        }
        /// <summary>
        /// Test the property 'DisclosedMethodOther'
        /// </summary>
        [Test]
        public void DisclosedMethodOtherTest()
        {
            // TODO unit test for the property 'DisclosedMethodOther'
        }
        /// <summary>
        /// Test the property 'DisclosureCreatedDate'
        /// </summary>
        [Test]
        public void DisclosureCreatedDateTest()
        {
            // TODO unit test for the property 'DisclosureCreatedDate'
        }
        /// <summary>
        /// Test the property 'EDisclosure'
        /// </summary>
        [Test]
        public void EDisclosureTest()
        {
            // TODO unit test for the property 'EDisclosure'
        }
        /// <summary>
        /// Test the property 'Forms'
        /// </summary>
        [Test]
        public void FormsTest()
        {
            // TODO unit test for the property 'Forms'
        }
        /// <summary>
        /// Test the property 'FulfillmentOrderedBy'
        /// </summary>
        [Test]
        public void FulfillmentOrderedByTest()
        {
            // TODO unit test for the property 'FulfillmentOrderedBy'
        }
        /// <summary>
        /// Test the property 'FulfillmentProcessedDate'
        /// </summary>
        [Test]
        public void FulfillmentProcessedDateTest()
        {
            // TODO unit test for the property 'FulfillmentProcessedDate'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedAPRField'
        /// </summary>
        [Test]
        public void LockedDisclosedAPRFieldTest()
        {
            // TODO unit test for the property 'LockedDisclosedAPRField'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedByField'
        /// </summary>
        [Test]
        public void LockedDisclosedByFieldTest()
        {
            // TODO unit test for the property 'LockedDisclosedByField'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedFinanceChargeField'
        /// </summary>
        [Test]
        public void LockedDisclosedFinanceChargeFieldTest()
        {
            // TODO unit test for the property 'LockedDisclosedFinanceChargeField'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedReceivedDate'
        /// </summary>
        [Test]
        public void LockedDisclosedReceivedDateTest()
        {
            // TODO unit test for the property 'LockedDisclosedReceivedDate'
        }
        /// <summary>
        /// Test the property 'ReceivedDate'
        /// </summary>
        [Test]
        public void ReceivedDateTest()
        {
            // TODO unit test for the property 'ReceivedDate'
        }
        /// <summary>
        /// Test the property 'DisclosureType'
        /// </summary>
        [Test]
        public void DisclosureTypeTest()
        {
            // TODO unit test for the property 'DisclosureType'
        }
        /// <summary>
        /// Test the property 'LeReason'
        /// </summary>
        [Test]
        public void LeReasonTest()
        {
            // TODO unit test for the property 'LeReason'
        }
        /// <summary>
        /// Test the property 'CdReason'
        /// </summary>
        [Test]
        public void CdReasonTest()
        {
            // TODO unit test for the property 'CdReason'
        }
        /// <summary>
        /// Test the property 'ChangeInCircumstance'
        /// </summary>
        [Test]
        public void ChangeInCircumstanceTest()
        {
            // TODO unit test for the property 'ChangeInCircumstance'
        }
        /// <summary>
        /// Test the property 'ChangeInCircumstanceComments'
        /// </summary>
        [Test]
        public void ChangeInCircumstanceCommentsTest()
        {
            // TODO unit test for the property 'ChangeInCircumstanceComments'
        }
        /// <summary>
        /// Test the property 'IntentToProceed'
        /// </summary>
        [Test]
        public void IntentToProceedTest()
        {
            // TODO unit test for the property 'IntentToProceed'
        }
        /// <summary>
        /// Test the property 'BorrowerDisclosedMethod'
        /// </summary>
        [Test]
        public void BorrowerDisclosedMethodTest()
        {
            // TODO unit test for the property 'BorrowerDisclosedMethod'
        }
        /// <summary>
        /// Test the property 'BorrowerDisclosedMethodOther'
        /// </summary>
        [Test]
        public void BorrowerDisclosedMethodOtherTest()
        {
            // TODO unit test for the property 'BorrowerDisclosedMethodOther'
        }
        /// <summary>
        /// Test the property 'BorrowerPresumedReceivedDate'
        /// </summary>
        [Test]
        public void BorrowerPresumedReceivedDateTest()
        {
            // TODO unit test for the property 'BorrowerPresumedReceivedDate'
        }
        /// <summary>
        /// Test the property 'BorrowerActualReceivedDate'
        /// </summary>
        [Test]
        public void BorrowerActualReceivedDateTest()
        {
            // TODO unit test for the property 'BorrowerActualReceivedDate'
        }
        /// <summary>
        /// Test the property 'CoborrowerDisclosedMethod'
        /// </summary>
        [Test]
        public void CoborrowerDisclosedMethodTest()
        {
            // TODO unit test for the property 'CoborrowerDisclosedMethod'
        }
        /// <summary>
        /// Test the property 'CoborrowerDisclosedMethodOther'
        /// </summary>
        [Test]
        public void CoborrowerDisclosedMethodOtherTest()
        {
            // TODO unit test for the property 'CoborrowerDisclosedMethodOther'
        }
        /// <summary>
        /// Test the property 'CoborrowerPresumedReceivedDate'
        /// </summary>
        [Test]
        public void CoborrowerPresumedReceivedDateTest()
        {
            // TODO unit test for the property 'CoborrowerPresumedReceivedDate'
        }
        /// <summary>
        /// Test the property 'CoborrowerActualReceivedDate'
        /// </summary>
        [Test]
        public void CoborrowerActualReceivedDateTest()
        {
            // TODO unit test for the property 'CoborrowerActualReceivedDate'
        }
        /// <summary>
        /// Test the property 'SnapshotFields'
        /// </summary>
        [Test]
        public void SnapshotFieldsTest()
        {
            // TODO unit test for the property 'SnapshotFields'
        }
        /// <summary>
        /// Test the property 'BorrowerType'
        /// </summary>
        [Test]
        public void BorrowerTypeTest()
        {
            // TODO unit test for the property 'BorrowerType'
        }
        /// <summary>
        /// Test the property 'CoborrowerType'
        /// </summary>
        [Test]
        public void CoborrowerTypeTest()
        {
            // TODO unit test for the property 'CoborrowerType'
        }
        /// <summary>
        /// Test the property 'ApplicationDate'
        /// </summary>
        [Test]
        public void ApplicationDateTest()
        {
            // TODO unit test for the property 'ApplicationDate'
        }
        /// <summary>
        /// Test the property 'DisclosedAPR'
        /// </summary>
        [Test]
        public void DisclosedAPRTest()
        {
            // TODO unit test for the property 'DisclosedAPR'
        }
        /// <summary>
        /// Test the property 'FinanceCharge'
        /// </summary>
        [Test]
        public void FinanceChargeTest()
        {
            // TODO unit test for the property 'FinanceCharge'
        }
        /// <summary>
        /// Test the property 'LoanProgram'
        /// </summary>
        [Test]
        public void LoanProgramTest()
        {
            // TODO unit test for the property 'LoanProgram'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Test]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'PropertyAddress'
        /// </summary>
        [Test]
        public void PropertyAddressTest()
        {
            // TODO unit test for the property 'PropertyAddress'
        }
        /// <summary>
        /// Test the property 'DateAdded'
        /// </summary>
        [Test]
        public void DateAddedTest()
        {
            // TODO unit test for the property 'DateAdded'
        }
        /// <summary>
        /// Test the property 'DisclosedDate'
        /// </summary>
        [Test]
        public void DisclosedDateTest()
        {
            // TODO unit test for the property 'DisclosedDate'
        }
        /// <summary>
        /// Test the property 'DisclosureMethod'
        /// </summary>
        [Test]
        public void DisclosureMethodTest()
        {
            // TODO unit test for the property 'DisclosureMethod'
        }
        /// <summary>
        /// Test the property 'LockedBorrowerPresumedReceivedDate'
        /// </summary>
        [Test]
        public void LockedBorrowerPresumedReceivedDateTest()
        {
            // TODO unit test for the property 'LockedBorrowerPresumedReceivedDate'
        }
        /// <summary>
        /// Test the property 'LockedBorrowerType'
        /// </summary>
        [Test]
        public void LockedBorrowerTypeTest()
        {
            // TODO unit test for the property 'LockedBorrowerType'
        }
        /// <summary>
        /// Test the property 'LockedCoborrowerPresumedReceivedDate'
        /// </summary>
        [Test]
        public void LockedCoborrowerPresumedReceivedDateTest()
        {
            // TODO unit test for the property 'LockedCoborrowerPresumedReceivedDate'
        }
        /// <summary>
        /// Test the property 'LockedCoborrowerType'
        /// </summary>
        [Test]
        public void LockedCoborrowerTypeTest()
        {
            // TODO unit test for the property 'LockedCoborrowerType'
        }
        /// <summary>
        /// Test the property 'DisclosedMethodName'
        /// </summary>
        [Test]
        public void DisclosedMethodNameTest()
        {
            // TODO unit test for the property 'DisclosedMethodName'
        }
        /// <summary>
        /// Test the property 'LenderTotalPaidOriginatorAmount'
        /// </summary>
        [Test]
        public void LenderTotalPaidOriginatorAmountTest()
        {
            // TODO unit test for the property 'LenderTotalPaidOriginatorAmount'
        }
        /// <summary>
        /// Test the property 'LoanPurchaseCredit'
        /// </summary>
        [Test]
        public void LoanPurchaseCreditTest()
        {
            // TODO unit test for the property 'LoanPurchaseCredit'
        }
        /// <summary>
        /// Test the property 'LoanClosingCost'
        /// </summary>
        [Test]
        public void LoanClosingCostTest()
        {
            // TODO unit test for the property 'LoanClosingCost'
        }
        /// <summary>
        /// Test the property 'LoanEstimate'
        /// </summary>
        [Test]
        public void LoanEstimateTest()
        {
            // TODO unit test for the property 'LoanEstimate'
        }
        /// <summary>
        /// Test the property 'PurchasePriceAmount'
        /// </summary>
        [Test]
        public void PurchasePriceAmountTest()
        {
            // TODO unit test for the property 'PurchasePriceAmount'
        }
        /// <summary>
        /// Test the property 'DisclosedSalesPrice'
        /// </summary>
        [Test]
        public void DisclosedSalesPriceTest()
        {
            // TODO unit test for the property 'DisclosedSalesPrice'
        }
        /// <summary>
        /// Test the property 'LoanFeesCityTaxBorPaidAmount'
        /// </summary>
        [Test]
        public void LoanFeesCityTaxBorPaidAmountTest()
        {
            // TODO unit test for the property 'LoanFeesCityTaxBorPaidAmount'
        }
        /// <summary>
        /// Test the property 'LoanFeesStateTaxBorPaidAmount'
        /// </summary>
        [Test]
        public void LoanFeesStateTaxBorPaidAmountTest()
        {
            // TODO unit test for the property 'LoanFeesStateTaxBorPaidAmount'
        }
        /// <summary>
        /// Test the property 'LoanGFEAgregateAdjustment'
        /// </summary>
        [Test]
        public void LoanGFEAgregateAdjustmentTest()
        {
            // TODO unit test for the property 'LoanGFEAgregateAdjustment'
        }
        /// <summary>
        /// Test the property 'LoanGFEGovernmentRecordingCharges'
        /// </summary>
        [Test]
        public void LoanGFEGovernmentRecordingChargesTest()
        {
            // TODO unit test for the property 'LoanGFEGovernmentRecordingCharges'
        }
        /// <summary>
        /// Test the property 'LoanSection1000SellerPaidTotalAmount'
        /// </summary>
        [Test]
        public void LoanSection1000SellerPaidTotalAmountTest()
        {
            // TODO unit test for the property 'LoanSection1000SellerPaidTotalAmount'
        }
        /// <summary>
        /// Test the property 'LoanAdjustmentsOtherCredits'
        /// </summary>
        [Test]
        public void LoanAdjustmentsOtherCreditsTest()
        {
            // TODO unit test for the property 'LoanAdjustmentsOtherCredits'
        }
        /// <summary>
        /// Test the property 'LoanDownPayment'
        /// </summary>
        [Test]
        public void LoanDownPaymentTest()
        {
            // TODO unit test for the property 'LoanDownPayment'
        }
        /// <summary>
        /// Test the property 'LoanFundsForBorrower'
        /// </summary>
        [Test]
        public void LoanFundsForBorrowerTest()
        {
            // TODO unit test for the property 'LoanFundsForBorrower'
        }
        /// <summary>
        /// Test the property 'LoanLineItemAmount'
        /// </summary>
        [Test]
        public void LoanLineItemAmountTest()
        {
            // TODO unit test for the property 'LoanLineItemAmount'
        }
        /// <summary>
        /// Test the property 'LoanRefinanceIncludingDebtsToBePaidOffAmount'
        /// </summary>
        [Test]
        public void LoanRefinanceIncludingDebtsToBePaidOffAmountTest()
        {
            // TODO unit test for the property 'LoanRefinanceIncludingDebtsToBePaidOffAmount'
        }
        /// <summary>
        /// Test the property 'LoanSellerCreditAmount'
        /// </summary>
        [Test]
        public void LoanSellerCreditAmountTest()
        {
            // TODO unit test for the property 'LoanSellerCreditAmount'
        }
        /// <summary>
        /// Test the property 'LoanTotalClosingCosts'
        /// </summary>
        [Test]
        public void LoanTotalClosingCostsTest()
        {
            // TODO unit test for the property 'LoanTotalClosingCosts'
        }
        /// <summary>
        /// Test the property 'DisclosedDailyInterest'
        /// </summary>
        [Test]
        public void DisclosedDailyInterestTest()
        {
            // TODO unit test for the property 'DisclosedDailyInterest'
        }
        /// <summary>
        /// Test the property 'AppliedCureAmount'
        /// </summary>
        [Test]
        public void AppliedCureAmountTest()
        {
            // TODO unit test for the property 'AppliedCureAmount'
        }
        /// <summary>
        /// Test the property 'LenderCompensationCreditAmount2'
        /// </summary>
        [Test]
        public void LenderCompensationCreditAmount2Test()
        {
            // TODO unit test for the property 'LenderCompensationCreditAmount2'
        }
        /// <summary>
        /// Test the property 'Line802LOCompAdditionalAmount1'
        /// </summary>
        [Test]
        public void Line802LOCompAdditionalAmount1Test()
        {
            // TODO unit test for the property 'Line802LOCompAdditionalAmount1'
        }
        /// <summary>
        /// Test the property 'Line802LOCompAdditionalAmount2'
        /// </summary>
        [Test]
        public void Line802LOCompAdditionalAmount2Test()
        {
            // TODO unit test for the property 'Line802LOCompAdditionalAmount2'
        }
        /// <summary>
        /// Test the property 'ChargesThatCannotDecreaseItemization9'
        /// </summary>
        [Test]
        public void ChargesThatCannotDecreaseItemization9Test()
        {
            // TODO unit test for the property 'ChargesThatCannotDecreaseItemization9'
        }
        /// <summary>
        /// Test the property 'ChargesThatCannotIncreaseItemization13'
        /// </summary>
        [Test]
        public void ChargesThatCannotIncreaseItemization13Test()
        {
            // TODO unit test for the property 'ChargesThatCannotIncreaseItemization13'
        }
        /// <summary>
        /// Test the property 'ChargesCannotIncrease10Itemization34'
        /// </summary>
        [Test]
        public void ChargesCannotIncrease10Itemization34Test()
        {
            // TODO unit test for the property 'ChargesCannotIncrease10Itemization34'
        }
        /// <summary>
        /// Test the property 'ChargesThatCannotDecreaseLE7'
        /// </summary>
        [Test]
        public void ChargesThatCannotDecreaseLE7Test()
        {
            // TODO unit test for the property 'ChargesThatCannotDecreaseLE7'
        }
        /// <summary>
        /// Test the property 'ChargesThatCannotIncreaseLE11'
        /// </summary>
        [Test]
        public void ChargesThatCannotIncreaseLE11Test()
        {
            // TODO unit test for the property 'ChargesThatCannotIncreaseLE11'
        }
        /// <summary>
        /// Test the property 'ChangesReceivedDate'
        /// </summary>
        [Test]
        public void ChangesReceivedDateTest()
        {
            // TODO unit test for the property 'ChangesReceivedDate'
        }
        /// <summary>
        /// Test the property 'RevisedDueDate'
        /// </summary>
        [Test]
        public void RevisedDueDateTest()
        {
            // TODO unit test for the property 'RevisedDueDate'
        }
        /// <summary>
        /// Test the property 'NumberOfDisclosureDocs'
        /// </summary>
        [Test]
        public void NumberOfDisclosureDocsTest()
        {
            // TODO unit test for the property 'NumberOfDisclosureDocs'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedDateField'
        /// </summary>
        [Test]
        public void LockedDisclosedDateFieldTest()
        {
            // TODO unit test for the property 'LockedDisclosedDateField'
        }
        /// <summary>
        /// Test the property 'LockedIntentReceivedByField'
        /// </summary>
        [Test]
        public void LockedIntentReceivedByFieldTest()
        {
            // TODO unit test for the property 'LockedIntentReceivedByField'
        }
        /// <summary>
        /// Test the property 'LockedDisclosedDailyInterestField'
        /// </summary>
        [Test]
        public void LockedDisclosedDailyInterestFieldTest()
        {
            // TODO unit test for the property 'LockedDisclosedDailyInterestField'
        }
        /// <summary>
        /// Test the property 'FulfillmentProcessedDateCoborrower'
        /// </summary>
        [Test]
        public void FulfillmentProcessedDateCoborrowerTest()
        {
            // TODO unit test for the property 'FulfillmentProcessedDateCoborrower'
        }
        /// <summary>
        /// Test the property 'FulfillmentOrderedByCoborrower'
        /// </summary>
        [Test]
        public void FulfillmentOrderedByCoborrowerTest()
        {
            // TODO unit test for the property 'FulfillmentOrderedByCoborrower'
        }
        /// <summary>
        /// Test the property 'AutomaticFulfillmentServiceName'
        /// </summary>
        [Test]
        public void AutomaticFulfillmentServiceNameTest()
        {
            // TODO unit test for the property 'AutomaticFulfillmentServiceName'
        }
        /// <summary>
        /// Test the property 'PresumedFulfillmentDate'
        /// </summary>
        [Test]
        public void PresumedFulfillmentDateTest()
        {
            // TODO unit test for the property 'PresumedFulfillmentDate'
        }
        /// <summary>
        /// Test the property 'ActualFulfillmentDate'
        /// </summary>
        [Test]
        public void ActualFulfillmentDateTest()
        {
            // TODO unit test for the property 'ActualFulfillmentDate'
        }
        /// <summary>
        /// Test the property 'CureAppliedToLenderCredit'
        /// </summary>
        [Test]
        public void CureAppliedToLenderCreditTest()
        {
            // TODO unit test for the property 'CureAppliedToLenderCredit'
        }
        /// <summary>
        /// Test the property 'CureAppliedToPrincipalReduction'
        /// </summary>
        [Test]
        public void CureAppliedToPrincipalReductionTest()
        {
            // TODO unit test for the property 'CureAppliedToPrincipalReduction'
        }
        /// <summary>
        /// Test the property 'UpdatedDateUtc'
        /// </summary>
        [Test]
        public void UpdatedDateUtcTest()
        {
            // TODO unit test for the property 'UpdatedDateUtc'
        }
        /// <summary>
        /// Test the property 'EdsRequestGuid'
        /// </summary>
        [Test]
        public void EdsRequestGuidTest()
        {
            // TODO unit test for the property 'EdsRequestGuid'
        }
        /// <summary>
        /// Test the property 'LinkedGuid'
        /// </summary>
        [Test]
        public void LinkedGuidTest()
        {
            // TODO unit test for the property 'LinkedGuid'
        }
        /// <summary>
        /// Test the property 'CdDateIssued'
        /// </summary>
        [Test]
        public void CdDateIssuedTest()
        {
            // TODO unit test for the property 'CdDateIssued'
        }
        /// <summary>
        /// Test the property 'ClosingDate'
        /// </summary>
        [Test]
        public void ClosingDateTest()
        {
            // TODO unit test for the property 'ClosingDate'
        }
        /// <summary>
        /// Test the property 'ActualLELoanAmountFromLatestRec'
        /// </summary>
        [Test]
        public void ActualLELoanAmountFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualLELoanAmountFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualLECD3TotalClosingCostJFromLatestRec'
        /// </summary>
        [Test]
        public void ActualLECD3TotalClosingCostJFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualLECD3TotalClosingCostJFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualLECD3TotalPayoffsAndPaymentsKFromLatestRec'
        /// </summary>
        [Test]
        public void ActualLECD3TotalPayoffsAndPaymentsKFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualLECD3TotalPayoffsAndPaymentsKFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLETotalClosingCostJFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLETotalClosingCostJFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLETotalClosingCostJFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLEClosingCostFinancedFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLEClosingCostFinancedFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLEClosingCostFinancedFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLEDepositFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLEDepositFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLEDepositFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLEFundForBorrowerFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLEFundForBorrowerFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLEFundForBorrowerFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLESellerCreditsFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLESellerCreditsFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLESellerCreditsFromLatestRec'
        }
        /// <summary>
        /// Test the property 'ActualSTDLEAdjustmentAndOtherCreditsFromLatestRec'
        /// </summary>
        [Test]
        public void ActualSTDLEAdjustmentAndOtherCreditsFromLatestRecTest()
        {
            // TODO unit test for the property 'ActualSTDLEAdjustmentAndOtherCreditsFromLatestRec'
        }
        /// <summary>
        /// Test the property 'StdAdjustmentAndOtherCreditsRemark'
        /// </summary>
        [Test]
        public void StdAdjustmentAndOtherCreditsRemarkTest()
        {
            // TODO unit test for the property 'StdAdjustmentAndOtherCreditsRemark'
        }
        /// <summary>
        /// Test the property 'LogIndicators'
        /// </summary>
        [Test]
        public void LogIndicatorsTest()
        {
            // TODO unit test for the property 'LogIndicators'
        }
        /// <summary>
        /// Test the property 'LineIndicators'
        /// </summary>
        [Test]
        public void LineIndicatorsTest()
        {
            // TODO unit test for the property 'LineIndicators'
        }

    }

}
