/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing DisclosureTracking2015ContractPropertyAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DisclosureTracking2015ContractPropertyAddressTests
    {
        // TODO uncomment below to declare an instance variable for DisclosureTracking2015ContractPropertyAddress
        //private DisclosureTracking2015ContractPropertyAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DisclosureTracking2015ContractPropertyAddress
            //instance = new DisclosureTracking2015ContractPropertyAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DisclosureTracking2015ContractPropertyAddress
        /// </summary>
        [Test]
        public void DisclosureTracking2015ContractPropertyAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DisclosureTracking2015ContractPropertyAddress
            //Assert.IsInstanceOfType<DisclosureTracking2015ContractPropertyAddress> (instance, "variable 'instance' is a DisclosureTracking2015ContractPropertyAddress");
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Test]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }
        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Test]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }

    }

}
