/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing LoanBatchUpdateRequestContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanBatchUpdateRequestContractTests
    {
        // TODO uncomment below to declare an instance variable for LoanBatchUpdateRequestContract
        //private LoanBatchUpdateRequestContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanBatchUpdateRequestContract
            //instance = new LoanBatchUpdateRequestContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanBatchUpdateRequestContract
        /// </summary>
        [Test]
        public void LoanBatchUpdateRequestContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanBatchUpdateRequestContract
            //Assert.IsInstanceOfType<LoanBatchUpdateRequestContract> (instance, "variable 'instance' is a LoanBatchUpdateRequestContract");
        }

        /// <summary>
        /// Test the property 'LoanGuids'
        /// </summary>
        [Test]
        public void LoanGuidsTest()
        {
            // TODO unit test for the property 'LoanGuids'
        }
        /// <summary>
        /// Test the property 'LoanData'
        /// </summary>
        [Test]
        public void LoanDataTest()
        {
            // TODO unit test for the property 'LoanData'
        }
        /// <summary>
        /// Test the property 'LoanFields'
        /// </summary>
        [Test]
        public void LoanFieldsTest()
        {
            // TODO unit test for the property 'LoanFields'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

    }

}
