/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing LoanContractProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractPropertyTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractProperty
        //private LoanContractProperty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractProperty
            //instance = new LoanContractProperty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractProperty
        /// </summary>
        [Test]
        public void LoanContractPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractProperty
            //Assert.IsInstanceOfType<LoanContractProperty> (instance, "variable 'instance' is a LoanContractProperty");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AssessorsParcelIdentifier'
        /// </summary>
        [Test]
        public void AssessorsParcelIdentifierTest()
        {
            // TODO unit test for the property 'AssessorsParcelIdentifier'
        }
        /// <summary>
        /// Test the property 'BlockIdentifier'
        /// </summary>
        [Test]
        public void BlockIdentifierTest()
        {
            // TODO unit test for the property 'BlockIdentifier'
        }
        /// <summary>
        /// Test the property 'BorrowerHomesteadIndicator'
        /// </summary>
        [Test]
        public void BorrowerHomesteadIndicatorTest()
        {
            // TODO unit test for the property 'BorrowerHomesteadIndicator'
        }
        /// <summary>
        /// Test the property 'BuildingStatusType'
        /// </summary>
        [Test]
        public void BuildingStatusTypeTest()
        {
            // TODO unit test for the property 'BuildingStatusType'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'CondotelIndicator'
        /// </summary>
        [Test]
        public void CondotelIndicatorTest()
        {
            // TODO unit test for the property 'CondotelIndicator'
        }
        /// <summary>
        /// Test the property 'ConstructionImprovementCostsAmount'
        /// </summary>
        [Test]
        public void ConstructionImprovementCostsAmountTest()
        {
            // TODO unit test for the property 'ConstructionImprovementCostsAmount'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Test]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'FinancedNumberOfUnits'
        /// </summary>
        [Test]
        public void FinancedNumberOfUnitsTest()
        {
            // TODO unit test for the property 'FinancedNumberOfUnits'
        }
        /// <summary>
        /// Test the property 'FloodCertificationIdentifier'
        /// </summary>
        [Test]
        public void FloodCertificationIdentifierTest()
        {
            // TODO unit test for the property 'FloodCertificationIdentifier'
        }
        /// <summary>
        /// Test the property 'FreCashOutAmount'
        /// </summary>
        [Test]
        public void FreCashOutAmountTest()
        {
            // TODO unit test for the property 'FreCashOutAmount'
        }
        /// <summary>
        /// Test the property 'GseRefinancePurposeType'
        /// </summary>
        [Test]
        public void GseRefinancePurposeTypeTest()
        {
            // TODO unit test for the property 'GseRefinancePurposeType'
        }
        /// <summary>
        /// Test the property 'GseTitleMannerHeldDescription'
        /// </summary>
        [Test]
        public void GseTitleMannerHeldDescriptionTest()
        {
            // TODO unit test for the property 'GseTitleMannerHeldDescription'
        }
        /// <summary>
        /// Test the property 'LandEstimatedValueAmount'
        /// </summary>
        [Test]
        public void LandEstimatedValueAmountTest()
        {
            // TODO unit test for the property 'LandEstimatedValueAmount'
        }
        /// <summary>
        /// Test the property 'LegalDescriptionText1'
        /// </summary>
        [Test]
        public void LegalDescriptionText1Test()
        {
            // TODO unit test for the property 'LegalDescriptionText1'
        }
        /// <summary>
        /// Test the property 'LegalDescriptionText2'
        /// </summary>
        [Test]
        public void LegalDescriptionText2Test()
        {
            // TODO unit test for the property 'LegalDescriptionText2'
        }
        /// <summary>
        /// Test the property 'LoanPurposeType'
        /// </summary>
        [Test]
        public void LoanPurposeTypeTest()
        {
            // TODO unit test for the property 'LoanPurposeType'
        }
        /// <summary>
        /// Test the property 'LotAcres'
        /// </summary>
        [Test]
        public void LotAcresTest()
        {
            // TODO unit test for the property 'LotAcres'
        }
        /// <summary>
        /// Test the property 'LotIdentifier'
        /// </summary>
        [Test]
        public void LotIdentifierTest()
        {
            // TODO unit test for the property 'LotIdentifier'
        }
        /// <summary>
        /// Test the property 'NameRecordingJurisdiction'
        /// </summary>
        [Test]
        public void NameRecordingJurisdictionTest()
        {
            // TODO unit test for the property 'NameRecordingJurisdiction'
        }
        /// <summary>
        /// Test the property 'NonwarrantableProjectIndicator'
        /// </summary>
        [Test]
        public void NonwarrantableProjectIndicatorTest()
        {
            // TODO unit test for the property 'NonwarrantableProjectIndicator'
        }
        /// <summary>
        /// Test the property 'NumberOfStories'
        /// </summary>
        [Test]
        public void NumberOfStoriesTest()
        {
            // TODO unit test for the property 'NumberOfStories'
        }
        /// <summary>
        /// Test the property 'OtherLoanPurposeDescription'
        /// </summary>
        [Test]
        public void OtherLoanPurposeDescriptionTest()
        {
            // TODO unit test for the property 'OtherLoanPurposeDescription'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'PriorLoanRecordationBookNumber'
        /// </summary>
        [Test]
        public void PriorLoanRecordationBookNumberTest()
        {
            // TODO unit test for the property 'PriorLoanRecordationBookNumber'
        }
        /// <summary>
        /// Test the property 'PriorLoanRecordationCurrentPrincipalAmount'
        /// </summary>
        [Test]
        public void PriorLoanRecordationCurrentPrincipalAmountTest()
        {
            // TODO unit test for the property 'PriorLoanRecordationCurrentPrincipalAmount'
        }
        /// <summary>
        /// Test the property 'PriorLoanRecordationOriginalPrincipalAmount'
        /// </summary>
        [Test]
        public void PriorLoanRecordationOriginalPrincipalAmountTest()
        {
            // TODO unit test for the property 'PriorLoanRecordationOriginalPrincipalAmount'
        }
        /// <summary>
        /// Test the property 'PriorLoanRecordationPageNumber'
        /// </summary>
        [Test]
        public void PriorLoanRecordationPageNumberTest()
        {
            // TODO unit test for the property 'PriorLoanRecordationPageNumber'
        }
        /// <summary>
        /// Test the property 'PropertyAcquiredYear'
        /// </summary>
        [Test]
        public void PropertyAcquiredYearTest()
        {
            // TODO unit test for the property 'PropertyAcquiredYear'
        }
        /// <summary>
        /// Test the property 'PropertyExistingLienAmount'
        /// </summary>
        [Test]
        public void PropertyExistingLienAmountTest()
        {
            // TODO unit test for the property 'PropertyExistingLienAmount'
        }
        /// <summary>
        /// Test the property 'PropertyLeaseholdExpirationDate'
        /// </summary>
        [Test]
        public void PropertyLeaseholdExpirationDateTest()
        {
            // TODO unit test for the property 'PropertyLeaseholdExpirationDate'
        }
        /// <summary>
        /// Test the property 'PropertyOriginalCostAmount'
        /// </summary>
        [Test]
        public void PropertyOriginalCostAmountTest()
        {
            // TODO unit test for the property 'PropertyOriginalCostAmount'
        }
        /// <summary>
        /// Test the property 'PropertyRightsType'
        /// </summary>
        [Test]
        public void PropertyRightsTypeTest()
        {
            // TODO unit test for the property 'PropertyRightsType'
        }
        /// <summary>
        /// Test the property 'PropertyUsageType'
        /// </summary>
        [Test]
        public void PropertyUsageTypeTest()
        {
            // TODO unit test for the property 'PropertyUsageType'
        }
        /// <summary>
        /// Test the property 'RefinanceImprovementCostsAmount'
        /// </summary>
        [Test]
        public void RefinanceImprovementCostsAmountTest()
        {
            // TODO unit test for the property 'RefinanceImprovementCostsAmount'
        }
        /// <summary>
        /// Test the property 'RefinanceImprovementsType'
        /// </summary>
        [Test]
        public void RefinanceImprovementsTypeTest()
        {
            // TODO unit test for the property 'RefinanceImprovementsType'
        }
        /// <summary>
        /// Test the property 'RefinancePropertyAcquiredYear'
        /// </summary>
        [Test]
        public void RefinancePropertyAcquiredYearTest()
        {
            // TODO unit test for the property 'RefinancePropertyAcquiredYear'
        }
        /// <summary>
        /// Test the property 'RefinancePropertyExistingLienAmount'
        /// </summary>
        [Test]
        public void RefinancePropertyExistingLienAmountTest()
        {
            // TODO unit test for the property 'RefinancePropertyExistingLienAmount'
        }
        /// <summary>
        /// Test the property 'RefinancePropertyOriginalCostAmount'
        /// </summary>
        [Test]
        public void RefinancePropertyOriginalCostAmountTest()
        {
            // TODO unit test for the property 'RefinancePropertyOriginalCostAmount'
        }
        /// <summary>
        /// Test the property 'RefinanceProposedImprovementsDescription'
        /// </summary>
        [Test]
        public void RefinanceProposedImprovementsDescriptionTest()
        {
            // TODO unit test for the property 'RefinanceProposedImprovementsDescription'
        }
        /// <summary>
        /// Test the property 'RuralAreaIndicator'
        /// </summary>
        [Test]
        public void RuralAreaIndicatorTest()
        {
            // TODO unit test for the property 'RuralAreaIndicator'
        }
        /// <summary>
        /// Test the property 'SectionIdentifier'
        /// </summary>
        [Test]
        public void SectionIdentifierTest()
        {
            // TODO unit test for the property 'SectionIdentifier'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'StreetAddress'
        /// </summary>
        [Test]
        public void StreetAddressTest()
        {
            // TODO unit test for the property 'StreetAddress'
        }
        /// <summary>
        /// Test the property 'StreetAddress2'
        /// </summary>
        [Test]
        public void StreetAddress2Test()
        {
            // TODO unit test for the property 'StreetAddress2'
        }
        /// <summary>
        /// Test the property 'StructureBuiltYear'
        /// </summary>
        [Test]
        public void StructureBuiltYearTest()
        {
            // TODO unit test for the property 'StructureBuiltYear'
        }
        /// <summary>
        /// Test the property 'TexasContinuousMoneyLoanIndicator'
        /// </summary>
        [Test]
        public void TexasContinuousMoneyLoanIndicatorTest()
        {
            // TODO unit test for the property 'TexasContinuousMoneyLoanIndicator'
        }
        /// <summary>
        /// Test the property 'TotalConstructionValueAmount'
        /// </summary>
        [Test]
        public void TotalConstructionValueAmountTest()
        {
            // TODO unit test for the property 'TotalConstructionValueAmount'
        }
        /// <summary>
        /// Test the property 'TypeRecordingJurisdiction'
        /// </summary>
        [Test]
        public void TypeRecordingJurisdictionTest()
        {
            // TODO unit test for the property 'TypeRecordingJurisdiction'
        }
        /// <summary>
        /// Test the property 'UnincorporatedAreaName'
        /// </summary>
        [Test]
        public void UnincorporatedAreaNameTest()
        {
            // TODO unit test for the property 'UnincorporatedAreaName'
        }
        /// <summary>
        /// Test the property 'ProdIsSpInUnderservedArea'
        /// </summary>
        [Test]
        public void ProdIsSpInUnderservedAreaTest()
        {
            // TODO unit test for the property 'ProdIsSpInUnderservedArea'
        }
        /// <summary>
        /// Test the property 'IsConstructionPhaseDisclosedSeparately'
        /// </summary>
        [Test]
        public void IsConstructionPhaseDisclosedSeparatelyTest()
        {
            // TODO unit test for the property 'IsConstructionPhaseDisclosedSeparately'
        }
        /// <summary>
        /// Test the property 'LinkedIsConstructionPhaseDisclosedSeparately'
        /// </summary>
        [Test]
        public void LinkedIsConstructionPhaseDisclosedSeparatelyTest()
        {
            // TODO unit test for the property 'LinkedIsConstructionPhaseDisclosedSeparately'
        }
        /// <summary>
        /// Test the property 'LinkedLoanPurposeType'
        /// </summary>
        [Test]
        public void LinkedLoanPurposeTypeTest()
        {
            // TODO unit test for the property 'LinkedLoanPurposeType'
        }

    }

}
