/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing LoanBatchUpdateStatusContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanBatchUpdateStatusContractTests
    {
        // TODO uncomment below to declare an instance variable for LoanBatchUpdateStatusContract
        //private LoanBatchUpdateStatusContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanBatchUpdateStatusContract
            //instance = new LoanBatchUpdateStatusContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanBatchUpdateStatusContract
        /// </summary>
        [Test]
        public void LoanBatchUpdateStatusContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanBatchUpdateStatusContract
            //Assert.IsInstanceOfType<LoanBatchUpdateStatusContract> (instance, "variable 'instance' is a LoanBatchUpdateStatusContract");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }

    }

}
