/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing LoanContractRegulationZRegulationZPayments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractRegulationZRegulationZPaymentsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractRegulationZRegulationZPayments
        //private LoanContractRegulationZRegulationZPayments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractRegulationZRegulationZPayments
            //instance = new LoanContractRegulationZRegulationZPayments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractRegulationZRegulationZPayments
        /// </summary>
        [Test]
        public void LoanContractRegulationZRegulationZPaymentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractRegulationZRegulationZPayments
            //Assert.IsInstanceOfType<LoanContractRegulationZRegulationZPayments> (instance, "variable 'instance' is a LoanContractRegulationZRegulationZPayments");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'InterestRatePercent'
        /// </summary>
        [Test]
        public void InterestRatePercentTest()
        {
            // TODO unit test for the property 'InterestRatePercent'
        }
        /// <summary>
        /// Test the property 'MonthlyPayment'
        /// </summary>
        [Test]
        public void MonthlyPaymentTest()
        {
            // TODO unit test for the property 'MonthlyPayment'
        }
        /// <summary>
        /// Test the property 'NumberOfPayments'
        /// </summary>
        [Test]
        public void NumberOfPaymentsTest()
        {
            // TODO unit test for the property 'NumberOfPayments'
        }
        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Test]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'RegulationZPaymentIndex'
        /// </summary>
        [Test]
        public void RegulationZPaymentIndexTest()
        {
            // TODO unit test for the property 'RegulationZPaymentIndex'
        }

    }

}
