/* 
 * Loan
 *
 * Returns the entire loan or specific entities of a loan.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Elli.Api.Loans.Api;
using Elli.Api.Loans.Model;
using Elli.Api.Loans.Client;
using System.Reflection;

namespace Elli.Api.Loans.Test
{
    /// <summary>
    ///  Class for testing LoanContractRegulationZRegulationZInterestRatePeriods
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoanContractRegulationZRegulationZInterestRatePeriodsTests
    {
        // TODO uncomment below to declare an instance variable for LoanContractRegulationZRegulationZInterestRatePeriods
        //private LoanContractRegulationZRegulationZInterestRatePeriods instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoanContractRegulationZRegulationZInterestRatePeriods
            //instance = new LoanContractRegulationZRegulationZInterestRatePeriods();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoanContractRegulationZRegulationZInterestRatePeriods
        /// </summary>
        [Test]
        public void LoanContractRegulationZRegulationZInterestRatePeriodsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanContractRegulationZRegulationZInterestRatePeriods
            //Assert.IsInstanceOfType<LoanContractRegulationZRegulationZInterestRatePeriods> (instance, "variable 'instance' is a LoanContractRegulationZRegulationZInterestRatePeriods");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AdjustmentDate'
        /// </summary>
        [Test]
        public void AdjustmentDateTest()
        {
            // TODO unit test for the property 'AdjustmentDate'
        }
        /// <summary>
        /// Test the property 'AdjustmentMonths'
        /// </summary>
        [Test]
        public void AdjustmentMonthsTest()
        {
            // TODO unit test for the property 'AdjustmentMonths'
        }
        /// <summary>
        /// Test the property 'InterestPayment'
        /// </summary>
        [Test]
        public void InterestPaymentTest()
        {
            // TODO unit test for the property 'InterestPayment'
        }
        /// <summary>
        /// Test the property 'InterestPrincipalPayment'
        /// </summary>
        [Test]
        public void InterestPrincipalPaymentTest()
        {
            // TODO unit test for the property 'InterestPrincipalPayment'
        }
        /// <summary>
        /// Test the property 'InterestRatePercent'
        /// </summary>
        [Test]
        public void InterestRatePercentTest()
        {
            // TODO unit test for the property 'InterestRatePercent'
        }
        /// <summary>
        /// Test the property 'MonthlyPayment'
        /// </summary>
        [Test]
        public void MonthlyPaymentTest()
        {
            // TODO unit test for the property 'MonthlyPayment'
        }
        /// <summary>
        /// Test the property 'PrincipalPayment'
        /// </summary>
        [Test]
        public void PrincipalPaymentTest()
        {
            // TODO unit test for the property 'PrincipalPayment'
        }
        /// <summary>
        /// Test the property 'RegulationZInterestRatePeriodType'
        /// </summary>
        [Test]
        public void RegulationZInterestRatePeriodTypeTest()
        {
            // TODO unit test for the property 'RegulationZInterestRatePeriodType'
        }
        /// <summary>
        /// Test the property 'TaxInsuranceAmount'
        /// </summary>
        [Test]
        public void TaxInsuranceAmountTest()
        {
            // TODO unit test for the property 'TaxInsuranceAmount'
        }
        /// <summary>
        /// Test the property 'TotalPayment'
        /// </summary>
        [Test]
        public void TotalPaymentTest()
        {
            // TODO unit test for the property 'TotalPayment'
        }

    }

}
